### ISSUE TITLE
Wallet not showing balance on testnet

### ISSUE THREAD

**Issue by MBuffenoir** [m2049r/xmrwallet#101]
Just sent moneroj to a newly created testnet wallet using v1.0.2
Backend is running on v0.11.0.0-release / testnet.

I can see the transactions coming in. But then if I wait a bit, then close and reopen the app my balance is still at 0.

Transactions were confirmed multiple times by now.

**Comment by m2049r** [comment]
are you on the "real" testnet or your own? the core monero code guesses the testnet block height - and if you are on your own testnet, it guesses wrong.

recover to new wallet from seed and enter the correct recovery height (or 0).

EDIT: it guesses wrong on all testnets. simply recover new testnet wallets from seed and correct restore height to workaround the issue.
