### ISSUE TITLE
Bug: LoginActivity::receive requires password.

### ISSUE THREAD

**Issue by jenniferberger** [m2049r/xmrwallet#123]
As a user i want to quickly share my public address with a customer.

(And I do not want my customer to know the balance of my account and I do not want to type in the password that unlocks the wallet)
I may have to give away the mobile as the user has a desktop only client and needs to type the public address.

Precondition:
User is on the login activity.
A wallet_item is configured.

Steps:
1. Click on wallet_item dots
   - see menu
2. Click on Receive

Expectation:
See dialog with QR-Code and copy able public address

Actual:
See password prompt, After password, the wallet is shown, not receive.

**Comment by m2049r** [comment]
the reason for the password prompt is that we need to unlock the wallet to get the wallet address (yes, the wallet address is shown in the wallet list, but this is just the contents of the address.txt file which could be anything).

after the steps you describe, the receive screen for the wallet opens - not the wallet screen (balance & transaction list). when it is closed you end up back in the wallet list. no senstive information is on the screen (only wallet name & wallet public address). no?

**Comment by jenniferberger** [comment]
i cannot reproduce the bug anymore with just the steps or anything else, sorry

using the info's from the wallet is a good thing, address.txt could be overwritten by malicious code that generated a address with a similar prefix.
The wallet is not open to anyone i give the phone while the receive dialog is open, password is re-requested when the wallet is opened.
So everything is alright, i close this ticket.
