### ISSUE TITLE
Bug: in give activity the amount validation happens too late.

### ISSUE THREAD

**Issue by jenniferberger** [m2049r/xmrwallet#129]
Steps to reproduce

1. open wallet
2. click give
3. scan address
4. enter amount '0.1'
5. click prepare

Expectation

Warning for no payment id
(Display of amount in last known conversion value)
(Display of amount in selected currency while typing the amount)

Actual

Amount input says 'Enter value' until i click into Payment Id

**Comment by m2049r** [comment]
it says "Enter value" if you have entered 0.1?

**Comment by jenniferberger** [comment]
Not sure, maybe the second input displays the message. The 'Enter value' message is between the first and second input field.
The second input is empty (as i did not select a currency and the last days it's very easy to estimate off the head)

**Comment by m2049r** [comment]
yes, clearly a bug.

**Comment by jenniferberger** [comment]
ui is redesigned, bug no longer valid
