### ISSUE TITLE
Bug: Restore watch only wallet from height scans all blocks

### ISSUE THREAD

**Issue by jenniferberger** [m2049r/xmrwallet#131]
Steps:

1. Create a wallet somewhere
2. Put a amount in that wallet
3. Record the Height for the confirmed transaction
4. Restore a view only wallet
5. Set the Height to the recorded height - 1(00)
6. Create wallet

Expectation:

The wallet displays the confirmed transaction very fast, almost no traffic occurs

Actual:

The wallet is restored from block 0 in 20k steps
Alot of traffic occurs

Restoring the donation wallet from height 0 on a 1mb/s line took at least 3 hours
Restoring a wallet with a height ~2017-06 took less than 30min
Restoring a wallet with a height about -1000 from current (took less than 5min)

Maybe the message during the skip forward (20k steps) should be 'finding height' and then 'scanning blocks'...

**Comment by m2049r** [comment]
this is "normal" monero behaviour. it is downloading the block hashes. as you say - it takes 5 minutes to sync a new wallet. and if you don't have the restore height it needs to download more and find your transactions.

is the problem the message displayed? it is actually scanning blocks :) maybe a warning dialog if you don't enter a block height would be better - simpler in any case!

**Comment by jenniferberger** [comment]
is there a state-difference in the backend for downloading the "huge" block vs downloading the "next" block?
the ux is better now as it displays '20k blocks remaining' (for yesterday date) immediately, but on a slow network connection (0.3mb/s) it takes 'too long' until something happens - looks crashed (which it is not as i can see on the network activity)
it would be nice to know (on a metered connection) that a huge download - estimate is fine - is in progress - so i can cancel it

**Comment by m2049r** [comment]
the message is updated as soon as the monero backend reports activity. until then it is silent. you are suggesting to show an estimate of the "blocks remaining" based on current time and already synced blockheight?

**Comment by jenniferberger** [comment]
current behavior is like this:
1. restore with height (yesterday)
2. ~20k blocks remaining is displayed
3. long wait time (until the backend returned that it found block -20k i guess)
4. counting down blocks until synced

the 'problem' imo with users is that they get impatient when nothing happens, especially when it costs them fiat money (metered connection, 100mb 'high speed' LTE packages) and all they see is the flashing traffic icon.

mhh, i browsed through the cpp code and see that there is no such api i guess the long time i am noticing is the history->refresh (Java_com_m2049r_xmrwallet_model_TransactionHistory_refreshJ) or wallet->refresh

so you cannot fix it with real good infos (percent complete and eta would be great)

maybe a manual measurement of traffic for some ranges (1k,10k,100k height differences) to produce a rough estimate how much data will be transferred and a hint how to speed things up (local node in wifi)
when the user is locked on the page for such a long time, give her something to read :)

i continue think about it, will have this slow network connection for some time and will generate more wallets, my initial reason for this ticket (counting up from 0) is resolved - estimates should be done in monero/cpp, they have the http method and access to counters.
