### ISSUE TITLE
Feature Request: Restore Height as Date

### ISSUE THREAD

**Issue by jenniferberger** [m2049r/xmrwallet#132]
The monero-wallet-cli allows entering a YYYY-MM-DD date as height.

Allow the user to enter a date as height during wallet restore.

**Comment by ehanoc** [comment]
I think this would be cool to have. But at the moment don't think that `wallet2::get_blockchain_height_by_date(uint16_t year, uint8_t month, uint8_t day)` is public api as in the current "wallet2_api.h".

We could propose the change, re-compile and add support for it. Or implement the conversion in the app too.

**Comment by m2049r** [comment]
if, i would submit a PR to monero-core. but the actual problem here is the UX/UI.

**Comment by jenniferberger** [comment]
restore wallet now has 'Restore Height or Date (YYYY-MM-DD)'
