### ISSUE TITLE
Security: Password visible, keyboard autocorrect & google button remains turned on

### ISSUE THREAD

**Issue by JollyMort** [m2049r/xmrwallet#136]
Android 7.1.1.

When creating a new wallet, the password is shown while typing. In addition to this, my autocorrect/google predictive search of the keyboard (gboard) remains turned on as if I'm inputting into any plaintext field. Some other apps correctly recognize/signal that it's sensitive info and automatically disable autocorrect/google predictive search of my keyboard. I don't want google snooping on my passwords.

**Comment by jenniferberger** [comment]
Indeed that also bugged me during testing, have no suggestions activated but that is a valid issue.

```
app/src/main/res/layout/fragment_generate.xml:52
-android:inputType="text"
+android:inputType="textVisiblePassword"
```
should fix this.
