### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by jonahar** [m2049r/xmrwallet#150]
I have two questions, I hope this is the right place to ask.

1. I noticed a very big wallet file (~45 MB) in the main app folder. This wallet is empty, no transactions at all.  For comparison, my desktop wallet file is no more than 5 MB (and it does have transactions information). Why is the app wallet file this big?

2. If I don't protect my wallet with an additional password inside the app, does that mean that the file is not encrypted and can be accessed by any other app with storage permissions?

**Comment by m2049r** [comment]
1. I just created a fresh wallet on Linux (cli) and the wallet cache is 49580796 bytes (47MB).
2. The keys file is encrypted with your wallet password (like in the official clients). There is no additional monerujo password. So if you have no password on your wallet, then yes, anyone with access to those files has access to your funds. of course, the same goes for the official desktop & cli clients. you need to use good passwords either way. Also make sure you have hardcopy backups of the seed & occasional off-mobile backups of the wallet files.

**Comment by jonahar** [comment]
Regarding 1, that's strange, I also created my wallet with cli on Linux. Do you know what information is stored there?

**Comment by m2049r** [comment]
are you sure you are synced? my understanding is that the cache file stores the hashes of all transactions to ensure the blockchain is intact. plus your wallet transactions.

**Comment by jonahar** [comment]
Yes, I am synced. I'm running a full node.
By "hashes of all transactions " do you mean all transactions in the network? If so, seems this information should be global to all wallets, and not linked to a specific wallet.

**Comment by m2049r** [comment]
yes i do. no it isn't . yes it should be. but that's how monero currently works.

**Comment by jonahar** [comment]
OK. Thank you for your help
