### ISSUE TITLE
Spend coins by scanning qr code - Enhancement

### ISSUE THREAD

**Issue by snoski3** [m2049r/xmrwallet#157]
I'm trying to think of how we can make monero easier to use for everyday uses. I know, just like everyone else.
There is a QR code to receive but no easy way to send. 
If I want to spend my monero at the "corner store", I would need to know their address.  Which would take a long time to type it in your wallet.
So how about a QR code scanner, then the fields would auto generate but would be read only, so you can't change the price on the merchant, except for the tip field.

**Comment by m2049r** [comment]
i don't quite understand - there is a qr code scanner on the first "send" page. on the next page you see the scanned amount which you can change if you want to.

**Comment by snoski3** [comment]
@m2049r 
I don't see the QR code for sending coin only receive. 
Can you upload a screenshot?

Thanks

**Comment by m2049r** [comment]
when you press "Give" in the wallet (tx list) the first screen which comes up is the address & payment id entry. there is a huge button in the middle of that labeled "SCAN". if you are on an old version the button is small and next to the address entry field.

**Comment by snoski3** [comment]
@m2049r 
I bet you think I'm blind. :-) I just realized, maybe I can't see it because I don't have any money in my wallet.

Ha.

Thanks for your help.

**Comment by snoski3** [comment]
@m2049r 
I just finished syncing the block and now the give button is there along with the scan button.

Thanks,
