### ISSUE TITLE
Problems with synchro of view-only wallet

### ISSUE THREAD

**Issue by hrumag** [m2049r/xmrwallet#158]
I'm trying to import a view-only wallet to Monerujo.

Say I've synchronized it till 200k blocks behind and I decide to close the wallet.
When the wallet is opened again, it re-starts synchronizing from 400k blocks behind (the block number differs every time). In several days I never managed to reach the current block.
 
When I connect either to a local Monero node on my LAN or to a remote node the behaviour is the same.

**Comment by rodentrabies** [comment]
Had the same problem, except I did actually finish sync process, but after closing the wallet no "wrapping up" notice was shown and after reentering, sync restarts at ~120000 block, and eventually slows down to the complete stop.

**Comment by rodentrabies** [comment]
Another device seems to work fine though.

**Comment by m2049r** [comment]
i cannot reproduce this behaviour - my best guess is that the node you used screwed something up. if you have more info please ass it here - e.g. if using your own fully synced node (from the beginning) leads to this issue as well.

**Comment by rodentrabies** [comment]
I used pre-filled node address, so I think it's not it, but I had some manual changes to the app directory in the file system (removing wallet backups etc), which may be the cause:
1. Add view-only wallet.
2. "Backup and delete" wallet.
3. Manually delete wallet backup files.
4. Add view-only wallet again (same seed, same passphrase).
5. Sync problem.

**Comment by m2049r** [comment]
it's the node. for sure. the "default node" points to a bunch of community nodes which may or may not be broken.
