### ISSUE TITLE
Mobile network slowness

### ISSUE THREAD

**Issue by Gingeropolous** [m2049r/xmrwallet#168]
I'm running 1.2.11 , and it seems that the wallet takes a really long time to connect to a remote node when using a mobile data network. (took about 4 minutes to get connected). I'm on an LTE network.

It is obviously really fast when using my wifi.

I'm wondering if its something on the wallet end. I remember at one point the Monero GUI had some problems with the DNS resolving when the GUI would start the daemon - is there any possibility that some aspect of the monero-wallet-cli (which i think this uses as its backend), has some weird DNS thingy going on.

On the other hand, I wonder if there's anything that can be done on the remote node end. Like, how could the servers be modified to make it faster?

**Comment by Gingeropolous** [comment]
nevermind, its slow on wifi too. It just gets that "connecting" thing and the bar keeps zooming back and forth. .. then it finally gets to scanning.

**Comment by azuremarty** [comment]
I was unable to replicate this on AT&T LTE. Wallet connects and syncs up quickly, within about 15 seconds. Using node.moneroworld.com:18089.

**Comment by Forage** [comment]
Looks like it's the node having problems. Try a different one, or setting up your own would be even better.

**Comment by Gingeropolous** [comment]
Right. I'm just concerned about the vast majority of Moneroju users that are just gonna select one from the dropdown. I'm trying to think if there's anything that can be done to make either end more responsive.

**Comment by SamsungGalaxyPlayer** [comment]
Is it possible to sample the block heights and connection speeds of several nodes on the MoneroWorld list? I imagine most users leave this as default.

**Comment by Gingeropolous** [comment]
> Is it possible to sample the block heights and connection speeds of several nodes on the MoneroWorld list? 

the node sniffers already check block heights, thats how they check if they are healthy. (of course, it'd be better to check hash, but even that could be spoofed). 

connection speeds are tough... because it'd be measured between the node sniffers node server and the remote node, not the user. Though, in general, this might be capable of determining if the remote node is on a good connection. But again, this is stuff on the node sniffer end, not the client (moneroju)

**Comment by m2049r** [comment]
i don't think we can do anything about this in the app.
