### ISSUE TITLE
[Feature] Toggle to only allow data over WiFi.

### ISSUE THREAD

**Issue by Forbo** [m2049r/xmrwallet#169]
I just checked my data usage for this cycle and Monerujo has eaten nearly a gig of my cap. Would we possibly be able to restrict the app to use data only when connected via WiFi?

**Comment by m2049r** [comment]
if you don't keep your wallet open there is no network traffic.

**Comment by Forbo** [comment]
I haven't used the wallet in a week. I am at home on a 1Gbit FTTH connection with 802.11ac wireless. Opening the app and getting it to the point where it is usable takes 9 minutes for it to sync. Not sure how long it would take on a connection that was worse, but I'd imagine it would be a bit longer. Don't know about you, but I'd rather not have to wait around that long any time I want to make a payment, as the "give" option doesn't appear until it is fully synced.

Maybe you use the wallet more often than I do, but I don't know many apps that make you wait that long for it to be usable. Just because it isn't _your_ use case doesn't mean it isn't a use case. Please reconsider the "wontfix". Even if it's an extremely low priority minor improvement that doesn't get addressed for who knows how long from now, at least acknowledge that this is an issue for some use cases.

**Comment by m2049r** [comment]
i am not sure i understand what you actually want. you need to be synced to send monero - on any client. that's how monero works. it takes 9 minutes for all of us.

your initial description implies your data usage is high - i suggested you sync only when on wifi.

what is "the issue" you are addressing?

**Comment by Forbo** [comment]
If I am able to leave the client running in the background, I can know it is ready to use whenever I need. If I can't leave it running all the time because it will chew up all my data, I now have to actively start/stop the client any time my WiFi connection is gained/lost. As such, I'm probably not going to launch the client unless I have a specific need to address at that time, because one mistake can end up costing a lot in overages.

Let's say that I I haven't used the client in three weeks, and I want to donate to a FFS real quick. What would have been a quick transaction if I can leave the client in the background actively syncing over WiFi now becomes at least a half hour ordeal. Forcing the user to micromanage the application will inhibit adoption and deter newcomers from engaging in the space.

**Comment by m2049r** [comment]
ok, now i understand what you are trying to do. this is not the intended use case.

do you know of any other app which keeps downloading stuff in the background around the clock over weeks?

**Comment by Forbo** [comment]
I can think of similar parallels with Google Photos and Nextcloud or other file syncing services. They both have options to allow sync only over WiFi. Some even have an option to only perform syncing when charging. Otherwise my Nextcloud would eat up all of my data when uploading photos and videos that I've taken throughout the day.

**Comment by m2049r** [comment]
yes, i know there are apps which allow you set to use wifi only. the question was specifically: do you know of any other app which keeps downloading stuff in the background around the clock over weeks?

keeping a wallet open over days/weeks is not the intended use case. you may want to be using mymonero in this scenario.

**Comment by Forbo** [comment]
Why does it matter whether it is upload or download? Data transfer is data transfer as far as a cap is concerned.

I guess I'm not understanding what the use case for Monerujo is, then. Can you explain why anyone would use Monerujo rather than just relying on MyMonero or a full wallet? Because apparently I'm doing it wrong.

**Comment by m2049r** [comment]
i don't know what more to tell you.

- keeping a wallet open over extended periods of time is bad OpSec.
- having a background service permanently downloading stuff is against android best practise (irrespective of a wifi constraint) - the examples of file syncing services do not apply here, because they sync files which have changed. the monero blockchain changes every two minutes, so its a permanent download. also the services you mention use a push mechanism to be notified when things change, then they connect, download & disconnect. monero would be connected to the daemon permanently.
- killing and restaring the wallet depending on wifi state is technically nontrivial. (this is the primary reason for #wontfix)
- monerujo use case is: sync your wallet every once in a while - like you would do on any other full client. so yes, you are doing it wrong.

**Comment by Forbo** [comment]
Thank you for taking the time to clarify and explain the reasoning behind the decision. I appreciate your time and efforts.
