### ISSUE TITLE
Missing incoming transactions on newly created wallet

### ISSUE THREAD

**Issue by amiuhle** [m2049r/xmrwallet#170]
I created a couple of new testnet wallets and sent some Monero to them shortly after I created them.

Monerujo missed those incoming transactions in all 4 wallets. Maybe you should start like 20k blocks before the current one when scanning newly created wallets.

**Comment by m2049r** [comment]
testnet wallet blockhieght of a new wallet is always wrong (also on official clients) because testnet does not have a constant blockheight, to use testnet wallets correctly you need to restore from seed. there is no option to specify blockheight for new wallets.
