### ISSUE TITLE
Wallet corrupted monero lost?

### ISSUE THREAD

**Issue by Onefox** [m2049r/xmrwallet#173]
I created a new wallet had the screen open, send some monero to the wallet, since this took a little bit i did some other things and my phone got to 5% battery...
I opens the wallet screen again and there was just the field where normally the public key of the wallet is shown. But there was just something about corrupted.

After that I added a power supply, charged the phone and reopened monerjo.
The wallet was gone...

Is there any place where i can look for the files or recover the wallet? I have the public address and the name i gave the wallet.

I lost some monero... :(

**Comment by Onefox** [comment]
I was so brave and tried to create a new wallet with the same name and I am getting the attempting to generate or restore wallet, but specified file(s) exist.  Exiting to not risk overwriting error,.
That sounds like hope to me.
The question is how to i access it?
Its not in the monerujo folder where all the other wallets are when I look on the files via data explorer.

**Comment by m2049r** [comment]
it's easiest if you restore your wallet from seed & use a new name. also use a restore height or it will take forever!
(the reason for the error message about the wallet existing is that there is a bug which does not delete halfcreated wallets and so they remain in internal storage)

**Comment by Onefox** [comment]
So is there a way to get the wallet from the internal storage?
I must admit i didn't safe the seed...

**Comment by m2049r** [comment]
send me a mail to help at monerujo io.

**Comment by m2049r** [comment]
and whatever you do, don't uninstall the app!

**Comment by Onefox** [comment]
Thanks,  i wrote you a email.
