### ISSUE TITLE
Signature mismatch, connection will be closed

### ISSUE THREAD

**Issue by SpliffyMap** [m2049r/xmrwallet#175]
I'm getting this error on Monero fork deamon. What's wrong?
![selection_023](https://user-images.githubusercontent.com/35120072/34698059-d2fbd490-f4de-11e7-978a-f5919c176c0d.png)'

"Signature mismatch, connection will be closed"

**Comment by m2049r** [comment]
maybe you are connecting a v7 daemon to a v6 network? or the other way around? in either case, it's not an xmrwallet issue. if you need further help with this please address it over at the monero project.
