### ISSUE TITLE
Support subaddresses

### ISSUE THREAD

**Issue by kelna** [m2049r/xmrwallet#176]
Please add support for subaddresses! I really miss this feature, since I would like to use one wallet for multiple projects. Thank you for the great work!

**Comment by kelna** [comment]
@m2049r will this be considered?

**Comment by m2049r** [comment]
yes it will :)

**Comment by xmr-karnal** [comment]
Is this about supporting sending to subaddresses or receiving to subaddresses?

(Or both!)

**Comment by m2049r** [comment]
well, it should be both. is there any reason to have only one direction? need to research how subaddresses are used irl.

**Comment by SamsungGalaxyPlayer** [comment]
@m2049r the application should support both creating subaddresses (to break address link when receiving funds) and sending to subaddresses (so people can send money to those using subaddresses).

**Comment by m2049r** [comment]
i think we will wait and see what is actually implemented in the next hardfork. and then follow. also how to handle 10k subaddresses UX/UI-wise may be a nightmare!

**Comment by kelna** [comment]
We had a beautiful hardfork today! :) What can we expect subaddress-wise? :)

**Comment by kelna** [comment]
Seriously tho. I'm not impatient, I just would like to know what to expect.

**Comment by m2049r** [comment]
no problem - expect nothing - at least until the next fork. we need to figure out how we can deal with this for an awesome UI/UX. maybe we can generate one-time-thow-away-subaddresses on the receive screen for the time being?

**Comment by kelna** [comment]
I think that would be just enough.

**Comment by Onefox** [comment]
I would also go that way, its more like bitcoin wallets are doing it, so some people already know that every time they receive coins, the receive address changes.
It could also be a setting, like "generate new address on receive" or something.

I mean, even if you sent to an address that was displayed earlier you would get the coins.
So sub-addresses just increase the security there.

**Comment by kelna** [comment]
The use-case for this feature is very simple: the user wants to publicise addresses under different nick names and he doesn't want those to be connected. Also he wants to receive his funds in one wallet. The above solution would solve this.

**Comment by m2049r** [comment]
implemented in #322 and release in v1.5.9

**Comment by kelna** [comment]
Very much appreciated, thank you, congrats and keep up the good work! :)

**Comment by ghost** [comment]
@m2049r I have a possible bug to report with subaddress. A sub address was generated. The tx to that sub address was picked up by the monero-wallet-cli, but never within the monerujo wallet. To have the tx show up within the monerujo gui, the wallet had to be deleted and then restored with seed. 
Should a new issue be created?

**Comment by SamsungGalaxyPlayer** [comment]
@tiedtoastar imo yes. This issue should be closed.
