### ISSUE TITLE
Feture request: add ability to sign off tx file

### ISSUE THREAD

**Issue by lessless** [m2049r/xmrwallet#179]
Hello,

This is a necessary for a business, when transactions are generated by the 3rd party software and coins holder can sigh them off in a bulk.

This feature is implemented in the desktop version under "Sign tx file" button.

**Comment by m2049r** [comment]
not sure this is a use case for a mobile wallet. can you please describe it in more detail?

**Comment by lessless** [comment]
@m2049r after reading around I saw a much better proposals with multisig transactions around here. Let me think a little more and come back with idea in a better shape :)

Cheers.
