### ISSUE TITLE
Restored wallet shows zero balance

### ISSUE THREAD

**Issue by AndreKoster** [m2049r/xmrwallet#196]
I have restored my wallet from the seed words on my new phone, but the balance shows zero. The wallet is still available on my old phone, and it shows the correct balance there.  The mnemonic seeds are absolutely correct (besides, if I had a mistake, the checksum would have failed). Also the public addess, view key, and spend key are identical on both phones. The same node and internet connection is used.

I suspect fault is in the restored wallet. But no idea how to make my balance appear.

**Comment by m2049r** [comment]
You probably used an incorrect (too high = recent) restore height. Check the block height of the first transaction in the old wallet and enter that - 1 as restore height in the new one.

**Comment by AndreKoster** [comment]
I used blockheight = 0 to set up the new instance of the wallet.  I'll delete it, and use a blockheight > 0 and < block of first tx and report the result.

**Comment by AndreKoster** [comment]
Using blockheight = 1 worked. So either starting at a block height of 0 means something else than starting at block 0, or there's a bug there.

**Comment by m2049r** [comment]
did you actually enter "0" into the field or did you leave it blank?

**Comment by azuremarty** [comment]
The burning question...

**Comment by AndreKoster** [comment]
As I recall, I did. At the time, I considered switching on my old phone to see at which block my very first tx had been. But I was lazy, and decided to just scan the whole chain. So I entered 0 (again, that's how I remember it). It can be easily checked by doing it again and entering 0 and nothing. However, for some reason the wallet can't connect with a node over my wifi at home and at my office. So I have to use my mobile data to use it. I've already used quite a lot data for scanning the whole chain twice, so I'm not very eager to do it once or twice more.

**Comment by m2049r** [comment]
@AndreKoster i looked at the code, and 0 is the default if you enter nothing. maybe the node you were using was "broken" the first time around. can you tell us how long it took you to scan the whole blockchain (from 0) and how much data it took?

people keep asking and i would like to add it to the faq!

**Comment by AndreKoster** [comment]
Looking at my data usage, I have to conclude that the first time NOT the whole blockchain was scanned. Monerujo used about 3.4 MB, but almost all of that the second time.

**Comment by m2049r** [comment]
3.4MB sounds very little!

**Comment by AndreKoster** [comment]
And yet, that's what it was.

https://imgur.com/a/tSiOo

**Comment by m2049r** [comment]
GB (not MB) - makes more sense. thanks.
