### ISSUE TITLE
boost build bootstrap.sh failed with  as: unrecognized option '--64'

### ISSUE THREAD

**Issue by bref2013** [m2049r/xmrwallet#201]
/opt/android/boost# ./bootstrap.sh
Building Boost.Build engine with toolset gcc... 
Failed to build Boost.Build build engine
Consult 'bootstrap.log' for more details

log:

###
rm -rf bootstrap
mkdir bootstrap
gcc -o bootstrap/jam0 command.c compile.c constants.c debug.c execcmd.c frames.c function.c glob.c hash.c hdrmacro.
c headers.c jam.c jambase.c jamgram.c lists.c make.c make1.c object.c option.c output.c parse.c pathsys.c regexp.c 
rules.c scan.c search.c subst.c timestamp.c variable.c modules.c strings.c filesys.c builtins.c class.c cwd.c nativ
e.c md5.c w32_getreg.c modules/set.c modules/path.c modules/regex.c modules/property-set.c modules/sequence.c modul
es/order.c execunix.c fileunix.c pathunix.c
as: unrecognized option '--64'
as: unrecognized option '--64'
as: unrecognized option '--64'
as: unrecognized option '--64'
as: unrecognized option '--64'
as: unrecognized option '--64'

Thanks a lot. I used ubuntu16

**Comment by m2049r** [comment]
check your $PATH - maybe you have the android toolchain in there. it should not be. start with a fresh shell.
