### ISSUE TITLE
monerujo.io Node & Monero Gui

### ISSUE THREAD

**Issue by juanpc2018** [m2049r/xmrwallet#202]
i have a Full Monero Wallet "Node", sync,
but monerujo does not connect to my Node.

user:pw@192.168.0.12:18081

Cannot Reach Node!
Try Again or Another.

but monerujo Works well with other Nodes,
i have also tryed Monero GUI as localhost / 127.0.0.1
and mining, but monerujo does not connect to my node wallet.

Wallet address are independent, 
Monero GUI has a different Address Wallet.

**Comment by m2049r** [comment]
either your phone is not on the same network as your server (is wifi on?) or you started the node in such a way that it does accept foreign connections or your server is set up to deny foreign connections (firewall settings?).
or none of the above.

**Comment by wenewzhang** [comment]
start the daemon with options:
--rpc-bind-ip 192.168.1.103 --rpc-bind-port 18081 --restricted-rpc --confirm-external-bind
then monerujo can works,192.168.1.103  is the ip address of the node

**Comment by juanpc2018** [comment]
Monero Gui Miner does not work if i set Daemon Address different than localhost/127.0.0.1

**Comment by juanpc2018** [comment]
daemond.exe Works well in cli mode, Gui has conflicts.

> monerod.exe --rpc-bind-ip 192.168.0.12 --rpc-bind-port 18081 --allow-local-ip --add-peer 192.168.0.12 --confirm-external-bind --restricted-rpc

monerujo seems to sync faster if daemond is
> start_mining 

monerujo node setting:
> 192.168.0.12:18081

simple, & Works.
