### ISSUE TITLE
Testnet: Incoming coins  lost in the monerujo create brand new wallet 

### ISSUE THREAD

**Issue by wenewzhang** [m2049r/xmrwallet#203]
The monerujo create new wallet, transfer 1 coin to the wallet,
the transaction show on the list 
but the balance and unconfirmed balance does’t  correct,
reopen the wallet, the coins disappear and the balance is ZERO,
if you recovery the wallet with 25-seeds,it’s synced the blockchains and  incoming coins get back,and then transfer coins to the wallet, the balance and transactions works fine!

redo:
1.create testnet
https://github.com/wenewzhang/private-testnet
2.start testate with and bind the rpc address 
./monerod --testnet --no-igd --hide-my-port --testnet-data-dir ~/testnet/node_01 --p2p-bind-ip 127.0.0.1 --log-level 0 --add-exclusive-node 127.0.0.1:38080 --add-exclusive-node 127.0.0.1:48080 --rpc-bind-ip 192.168.1.104 --restricted-rpc --confirm-external-bind
3.start monerujo connect to 192.168.1.104

**Comment by m2049r** [comment]
yes, the testnet calculations for blockheight of new wallets don't work. same happens with the official wallets (e.g. cli).

**Comment by wenewzhang** [comment]
It's a bad experience for new users,any idea how to improve it ?

**Comment by m2049r** [comment]
you are right, but i don't think it can be changed as wallets are made offline and have to guess the blockheight by some formula using blocks/time. testnet is totally uncontrollable in the respect. mainnet has its 2 minutes ...

**Comment by wenewzhang** [comment]
Acctually,the mainnet has the same problem!
:)
