### ISSUE TITLE
Fee too high (Priority Low)

### ISSUE THREAD

**Issue by juanpc2018** [m2049r/xmrwallet#211]
call me crazy, but a fee of 0.0025-0.0029 XMR seem too mucho!
Ringsize5-Ringsize 26.
that was one of the problems with Bitcoin, & one of the reasons Bitcoin Cash was born.

if Bitcoin dies, and Monero becomes the New Standard. or if XMR price reach BTC price today.
0.0025 will become $2Ousd. Fee. for a $8Ousd. transaction. 25% is crazy.

WesternUnion will go extinct like BlockBuster, Only if fees are Lower.
WU fee is 1%~3%.

¿is this a Monerujo problem or a Monero design flaw? i´m New to this.
How much is the Monero Coin limit?
something is not right, does not add up.

**Comment by m2049r** [comment]
what @moneromooo-monero said
