### ISSUE TITLE
Latest update (beta stream) crashes on open or create 

### ISSUE THREAD

**Issue by stevesbrain** [m2049r/xmrwallet#220]
Hey all, I'm in the beta stream, and just received the update for the 0.12 support. I can't open my wallet - crashes with either correct or incorrect password as soon as you click "okay" - and I cannot create a new wallet (crashes as soon as I click the create button after entering a password). Let me know what you need from me :)

**Comment by m2049r** [comment]
Thanks for the info - which version exactly (About... in first screen)? What phone & Android Version? Thanks.

**Comment by m2049r** [comment]
never mind - i figured it out!

**Comment by m2049r** [comment]
@stevesbrain can you please test with latest release?

**Comment by stevesbrain** [comment]
@m2049r Absolutely; will test now :)

Edit: Can confirm all working now! Thanks for the quick response on that :grin:
