### ISSUE TITLE
support for Bytecoin BCN

### ISSUE THREAD

**Issue by juanpc2018** [m2049r/xmrwallet#225]
Bytecoin BCN has a very similar architecture to MoneroXMR,

actually Monero is a Mutation of BCN.
making a Bytecoin BCN wallet should be possible...
https://upload.wikimedia.org/wikipedia/commons/7/7a/Forks-tree-fixed.png

XMR Wallet could become a multi-wallet,
or a fork to a new bcnwallet ?

Monero high fee, makes 
BCN look interesting.
https://github.com/bcndev

Jaxx & Coinomi "The Most Popular Multi-Wallets" "haven´t tested exodus,"
they won´t support CryptoNight coins because its a completely different architecture...
Jaxx has tried and failed to support XMR .

https://blog.jaxx.io/jaxx-monero-integration-update/
https://cointelegraph.com/news/jaxx-cancels-monero-integration-cites-difficulties-working-with-community

**Comment by SamsungGalaxyPlayer** [comment]
[I have a strong suspicion this will not happen](https://monero.stackexchange.com/questions/852/what-is-the-origin-of-monero-and-its-relationship-to-bytecoin).

**Comment by m2049r** [comment]
Not everything which can be done should be done.
