### ISSUE TITLE
Feature suggest:fingerprint login method

### ISSUE THREAD

**Issue by qxxrbull** [m2049r/xmrwallet#229]
The only one way to login wallet is password now.
I think it can support both password and fingerprint login method.

**Comment by m2049r** [comment]
both together or either one?

**Comment by qxxrbull** [comment]
Either one

**Comment by jonathancross** [comment]
https://github.com/m2049r/xmrwallet/pull/244 has been merged.
@qxxrbull Please test when possible.

**Comment by m2049r** [comment]
yes, please test on https://github.com/m2049r/xmrwallet/releases/tag/v1.5.2 (warning: it's fantastic!)

**Comment by qxxrbull** [comment]
It seems have some problem on my Lemobile Le x820 (pixel experience rom Android 8.1.0 Oreo)
When I use fingerprint to login my wallet. It gets force close forever. But using password is OK.

**Comment by 0140454** [comment]
@qxxrbull 

Could you attach ```adb logcat``` output generated at force close?

**Comment by qxxrbull** [comment]
[1.txt](https://github.com/m2049r/xmrwallet/files/1977816/1.txt)

**Comment by qxxrbull** [comment]
[1.txt](https://github.com/m2049r/xmrwallet/files/1977820/1.txt)

**Comment by qxxrbull** [comment]
Seems it have some privacy information in it . So I just privode xmrwallet part. If need more information. pleast tell me.
 
[logcat.txt](https://github.com/m2049r/xmrwallet/files/1977855/logcat.txt)

**Comment by m2049r** [comment]
looks like
```String encoded = context.getSharedPreferences(SecurityConstants.WALLET_PASS_PREFS_NAME, Context.MODE_PRIVATE).getString(wallet, "");``` in ```KeyStoreHelper.loadWalletUserPass()```
is empty?

Maybe ```FingerprintHelper.isFingerprintAuthAllowed()``` should also check if there is an entry? Then again, how can the key exist and the encoded entry not? If this is really the case, it should remove the key as well ...

**Comment by 0140454** [comment]
It seems that the activity had been detached when user changed password. Therefore, ```getActivity()``` invoked in ```AsyncChangePassword.doInBackground``` return **null**, and ```saveWalletUserPass()``` failed to save password.
In this situation, there is a key, but no cipher text.

**Comment by m2049r** [comment]
so if @qxxrbull opens the wallet with password, and changes the password & enables fingerprint (again) it should work for them?
i don't think ```getActivity()``` can return **null**.

**Comment by 0140454** [comment]
I think I need @qxxrbull  to describe how to reproduce this bug. Because I cannot reproduce it on my phone. Maybe there are situations I missed.

**Comment by qxxrbull** [comment]
OK, it's done after I changed the password.

**Comment by qxxrbull** [comment]
I think maybe it's because I directly update the new version that cause this situation.

**Comment by jenniferberger** [comment]
updated via fdroid
changed passphrase and enabled fingerprint (little bit hard to find as subaction in details, but ok)
close wallet
open wallet used registered finger: ok
open wallet used unregistered finger: ok (not accepted)
open wallet used passphrase: ok
open wallet used incorrect passphrase: ok (not accepted)
android 7.1 / nokia 6

great work, thank you!

**Comment by 0140454** [comment]
@jenniferberger 
Thanks for testing

@qxxrbull 
Both of creating wallet and changing password would call ```saveWalletUserPass```.
Could you test these functions again to confirm this bug is gone?

**Comment by qxxrbull** [comment]
@0140454
OK, I tested and the bug is gone.

**Comment by m2049r** [comment]
@jenniferberger @qxxrbull @0140454 i refactored the fingerprint code quite a bit on the basis of crashes reported on google play. could you please test the 1.5.3 release? make sure to write down your seeds/recovery passwords before upgrade - just in case the keys get lost.

**Comment by 0140454** [comment]
It works great!

Test Steps:

1. Open wallet
2. Change password with fingerprint disabled and close wallet - OK
3. Open wallet using password - OK
4. Change password with fingerprint enabled and close wallet - OK
5. Open wallet using password and close wallet - OK
6. Open wallet using fingerprint and close wallet - OK
7. Open wallet using wrong password - OK (Not accepted)
8. Open wallet using unregistered fingerprint - OK (Not accepted)
9. Rename wallet
10. Open wallet using password and close wallet - OK
11. Open wallet using fingerprint - OK
12. Ask password when sending funds or viewing details - Yes

Environment:

* Pixel 2 XL (Android 8.1.0)

**Comment by m2049r** [comment]
@0140454 excellent - thanks a lot!

**Comment by 0140454** [comment]
You're welcome.
But because I cannot reproduce this bug at the beginning, maybe we should wait for others' test result to make sure it has been fixed.

**Comment by qxxrbull** [comment]
I tried 
1.New install. And creative a new wallet
2.Update from old version 

Everything about access to account works well. No FC or error.

Everything looks OK , thanks.

Environment:
LeMobile Le X820 (Android 8.1.0 pixel experience rom)
ASUS ZE551ML (Official stock ROM)
