### ISSUE TITLE
Cannot reach node Or zero XMR and no transaction on wallet after reinstall

### ISSUE THREAD

**Issue by minzak** [m2049r/xmrwallet#237]
I'm cleaned some files via native system tool on Android8.
After in i can't connect with wallet - popup grey message "**Cannot connect node! Try again or another**"
I also trying reinstall - still problem.
I also found all wallet files, deleted all from one wallet, manually restore wallet - still problem.
Also trying delete app cache and data - still problem.

I use
**geo.node.moneroworld.com at port 18089
node.moneroworld.com at port 18089
node.xmrbackb.one at port 18081**
How to fresh and restore ?
[SVID_20180420_203923.zip](https://github.com/m2049r/xmrwallet/files/1933300/SVID_20180420_203923.zip)

Other wallets and app still work.

**Comment by minzak** [comment]
After fully deleted 2 folders with keys and etc - all is fine.
But how to restore balance? still zero, but if i check on explorer via hash - i see all transactions.
How to restore payment transaction in wallet?

**Comment by m2049r** [comment]
if you restore the same wallet on official gui with the same parameters (node & restore height) it works?

**Comment by minzak** [comment]
Yes, after restore on Monero GUI - all XMR are present.
Only on this mobile wallet zero balance, i do not want to use non-official wallet.

**Comment by m2049r** [comment]
@moneromooo-monero is there any chance this (zero balance - not the "cannot reach node") can have something to do with the latest commits on the release 0.12 branch? (i think i am the only one using them in production)

**Comment by minzak** [comment]
No, now with connect all is fine. Sync chain is fine, now 1556299 blocks. 
And latest version 1.4.7 from PlayMarket
And local new GUI 0.12.0.0 Lithium Luna

![capture](https://user-images.githubusercontent.com/12154217/39088574-2b00af7e-45bd-11e8-98c4-f6b29f193574.PNG)

![23f21a12-cd07-47fe-8513-4217a77ab329](https://user-images.githubusercontent.com/12154217/39088658-c1c21032-45be-11e8-9467-2eef551dfea4.jpg)
![131d27dd-4810-43f2-8d12-908ad0024a71](https://user-images.githubusercontent.com/12154217/39088659-c1dbc07c-45be-11e8-8d62-5050789e64cb.jpg)
![93901d05-53f4-4b71-8360-690573a03bc9](https://user-images.githubusercontent.com/12154217/39088660-c1f56fb8-45be-11e8-8c47-c07c956261a2.jpg)
![c1af40cf-f51d-43e4-809c-21b6f76f1a03](https://user-images.githubusercontent.com/12154217/39088661-c20f4514-45be-11e8-9ebd-48c38c713546.jpg)
![untitled](https://user-images.githubusercontent.com/12154217/39088712-91b5a114-45bf-11e8-9ca4-6b00592a5317.png)

**Comment by m2049r** [comment]
i just created a new wallet and transfered into it without any problem. recovering from seed also works perfectly (with correct balance). so i am guessing the node you are using is broken. it appears that you are using a local node with the GUI - but a public one for Monerujo. so my question again:
> if you restore the same wallet on official gui with the same parameters (node & restore height) it works?

**Comment by minzak** [comment]
YES, i fully deleted all.
And install again and restore view-only wallet, sync was very fast, near 25-45 sec. Why scaned ~22000 chains, not ~1500000 ?
I use standard default node - node.moneroworld.com:18089 (not local!) I also reconnect to other node - same result. How to rescan from 1 chain?
P.S. i can write video.

**Comment by m2049r** [comment]
the superfast restore is normal.

when you sync your desktop GUI with node.moneroworld.com:18089 and then restore the wallet it works or not?

**Comment by minzak** [comment]
I delete wallet, restore wallet and chose remote node - node.moneroworld.com:18089 and all is work.

![3](https://user-images.githubusercontent.com/12154217/39121729-295bf126-46fb-11e8-90bf-031c8d6d5fec.PNG)
![4](https://user-images.githubusercontent.com/12154217/39121730-29765e12-46fb-11e8-9a59-746ebd38cf2d.PNG)

**Comment by m2049r** [comment]
this makes no sense. the only difference is that we use the newest v0.12 code. @moneromooo-monero ideas? if this is indeed a real problem, maybe it should be resolved before the official GUI adopts it @dEBRUYNE-1.

**Comment by minzak** [comment]
I know, it really strange. any debug mode? How to rescan exact chain with transaction with my xmr?

**Comment by m2049r** [comment]
just copy your wallet files from the PC into the monerujo folder on your Android device.

**Comment by minzak** [comment]
again restore from seed, result the same, no xmr. on other PC with previous GUI, everything is working. only mobile is not synced, need logging.

**Comment by m2049r** [comment]
what is the restore height you use?

**Comment by minzak** [comment]
i not use height, all by default.

**Comment by minzak** [comment]
is possible to use height in mobile wallet? For scan balance from genesis block. Because on powered PC much time needed for scanning. Honestly I'm not believe in scan for 1 min on mobile.....

**Comment by m2049r** [comment]
do not scan from 0 - enter height of first block or date of your first transaction!

**Comment by minzak** [comment]
It is not matter about GUI. All is work on desktop.
I cant scan from X block in mobile wallet , i not see menu for this.
Need new talkalative version with logging or else.
What i can to do - to helps resolve it?

**Comment by m2049r** [comment]
block height is the field just below the mnemonic seed entry.

**Comment by minzak** [comment]
At last!
I found what is it been.
When network drops, unstable or etc - wallet not get error - just say synced.
When i use nice, stable network - all is fine. And syn is not fast in this time.
