### ISSUE TITLE
Build OpenSSL error 

### ISSUE THREAD

**Issue by Onefox** [m2049r/xmrwallet#246]
I try to build a development environment under a new ubuntu 16.04 VM with ndk r16.

When building OpenSSL I get some beginner error I guess,

I don't really know what dependences I am missing.
Here is the log:
https://pastebin.com/4F7GsNge

**Comment by 0140454** [comment]
You need to specify include path in ```build-all-arch.sh``` because some headers have been unified. ([Reference](https://android.googlesource.com/platform/ndk/+/ndk-release-r16/CHANGELOG.md))

Here is the patch: https://pastebin.com/9nHvt3Zh

**Comment by m2049r** [comment]
is this the only change needed for a ndk r16 build?

**Comment by Onefox** [comment]
Thank you!

This should be added than to the https://github.com/m2049r/android-openssl
repo or?

**Comment by 0140454** [comment]
For NDK r16 build,

* Build environment
  * Ubuntu 17.10
  * cmake 3.9.1

* OpenSSL
  I need to apply the above-mentioned patch.

* Boost
  No problem.

* Monero
  I need to add ```OPENSSL_INCLUDE_DIR``` to cmake command to ensure it will get correct OpenSSL version.
  ```diff
  diff --git a/build-all-arch.sh b/build-all-arch.sh
  index 8d5e48dc..df228a06 100755
  --- a/build-all-arch.sh
  +++ b/build-all-arch.sh
  @@ -44,8 +44,8 @@ for arch in ${archs[@]}; do
          mkdir -p $OUTPUT_DIR
          cd $OUTPUT_DIR
   
  -       PATH=/opt/android/tool/$arch/$target_host/bin:/opt/android/tool/$arch/bin:$PATH CC=clang CXX=clang++ cmake -D BUILD_GUI_DEPS=1 -D BUILD_TESTS=OFF -D ARCH="$xarch" -D STATIC=ON -D BUILD_64=$sixtyfour -D CMAKE_BUILD_TYPE=$build_type -D ANDROID=true -D BUILD_TAG="android" -D BOOST_ROOT=/opt/android/build/boost/$arch -D BOOST_LIBRARYDIR=/opt/android/build/boost/$arch/lib -D OPENSSL_ROOT_DIR=/opt/android/build/openssl/$arch -D OPENSSL_CRYPTO_LIBRARY=/opt/android/build/openssl/$arch/lib/libcrypto.so -D OPENSSL_SSL_LIBRARY=/opt/android/build/openssl/$arch/lib/libssl.so -D CMAKE_POSITION_INDEPENDENT_CODE:BOOL=true ../..
  +       PATH=/opt/android/tool/$arch/$target_host/bin:/opt/android/tool/$arch/bin:$PATH CC=clang CXX=clang++ cmake -D BUILD_GUI_DEPS=1 -D BUILD_TESTS=OFF -D ARCH="$xarch" -D STATIC=ON -D BUILD_64=$sixtyfour -D CMAKE_BUILD_TYPE=$build_type -D ANDROID=true -D BUILD_TAG="android" -D BOOST_ROOT=/opt/android/build/boost/$arch -D BOOST_LIBRARYDIR=/opt/android/build/boost/$arch/lib -D OPENSSL_ROOT_DIR=/opt/android/build/openssl/$arch -D OPENSSL_INCLUDE_DIR=/opt/android/build/openssl/$arch/include -D OPENSSL_CRYPTO_LIBRARY=/opt/android/build/openssl/$arch/lib/libcrypto.so -D OPENSSL_SSL_LIBRARY=/opt/android/build/openssl/$arch/lib/libssl.so -D CMAKE_POSITION_INDEPENDENT_CODE:BOOL=true ../..
          find . -path ./lib -prune -o -name '*.a' -exec cp '{}' lib \;
 
       TARGET_LIB_DIR=/opt/android/build/monero/$arch/lib
  ```

  When compiling monero, I will get error message as the following:
  ```
  /opt/android/monero/src/crypto/random.c:73:5: error: implicit declaration of function 'err' is invalid in C99
  ```
  After the investigation, it is because Clang finds **err.h** in openssl directory first, rather than NDK directory.
  Because I have no idea how to rearrange include path, I just disable related warnings to skip this error temporarily. :(

**Comment by Onefox** [comment]
I think here is also something missing:

And finally: Build Monero
cd /opt/android
git clone https://github.com/m2049r/monero.git

cd /opt/android/monero/build
./build-all-arch.sh


The build folder is not there yet also the build-all-arch.sh file is missing in there... Or is it the same as in the android openssl folder?

**Comment by 0140454** [comment]
I use branch ```release-v0.12-monerujo``` to build monero.
That file is in root directory.

**Comment by Onefox** [comment]
Thanks, one step at a time, sorry for bothering, I am now getting the following when building the branch via the script:
https://pastebin.com/NhLSffTr
And this is the CMakeError.log
https://pastebin.com/3QvNyhaC
And the  CMakeOutput.log
https://pastebin.com/DYiDjgm4

Thanks in advanced

**Comment by 0140454** [comment]
You also need to clone sub-module ```unbound```.

Try the following commands in root directory:
```shell
git submodule init
git submodule update
```

**Comment by Onefox** [comment]
How did you disable the random.c.o failed error?

I am getting:
[ 16%] Building C object external/unbound/CMakeFiles/unbound.dir/iterator/iter_hints.c.o
src/crypto/CMakeFiles/obj_cncrypto.dir/build.make:422: recipe for target 'src/crypto/CMakeFiles/obj_cncrypto.dir/random.c.o' failed
CMakeFiles/Makefile2:805: recipe for target 'src/crypto/CMakeFiles/obj_cncrypto.dir/all' failed

**Comment by 0140454** [comment]
I use the following patch to turn off related warning.
There may be other elegant ways to fix it, but I have no idea currently.

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index f2350281..b94d1403 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -489,7 +489,7 @@ else()
   else()
     set(ARCH_FLAG "-march=${ARCH}")
   endif()
-  set(WARNINGS "-Wall -Wextra -Wpointer-arith -Wundef -Wvla -Wwrite-strings -Wno-error=extra -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-unused-variable -Wno-error=unused-variable -Wno-error=undef -Wno-error=uninitialized")
+  set(WARNINGS "-Wall -Wextra -Wpointer-arith -Wundef -Wvla -Wwrite-strings -Wno-error=extra -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-unused-variable -Wno-error=unused-variable -Wno-error=undef -Wno-error=uninitialized -Wno-error=implicit-function-declaration -Wno-error=user-defined-warnings")
   if(NOT MINGW)
     set(WARNINGS_AS_ERRORS_FLAG "-Werror")
   endif()
@@ -512,7 +512,7 @@ else()
       add_definitions(-DWINVER=0x0501 -D_WIN32_WINNT=0x0501)
     endif()
   endif()
-  set(C_WARNINGS "-Waggregate-return -Wnested-externs -Wold-style-definition -Wstrict-prototypes")
+  set(C_WARNINGS "-Waggregate-return -Wnested-externs -Wold-style-definition")
   set(CXX_WARNINGS "-Wno-reorder -Wno-missing-field-initializers")
   try_compile(STATIC_ASSERT_RES "${CMAKE_CURRENT_BINARY_DIR}/static-assert" "${CMAKE_CURRENT_SOURCE_DIR}/cmake/test-static-assert.c" COMPILE_DEFINITIONS "-std=c11")
   if(STATIC_ASSERT_RES)
```

**Comment by Onefox** [comment]
With this steps I am now able to build a debug APK and deploy it on my phone, thank you very much!

**Comment by m2049r** [comment]
I applied the openssl patch to the https://github.com/m2049r/android-openssl
the rest I will look at later.
thanks!

**Comment by 0140454** [comment]
About building Monero,

* I need to add ```OPENSSL_INCLUDE_DIR``` in cmake command
  I found that ```OPENSSL_INCLUDE_DIR``` should be the same as ```OPENSSL_ROOT_DIR```.
  This will prevent Clang from including wrong **err.h** when compiling crypto/random.o.

* Compilation error
  But there is still an error at compilation:
  ```
  /opt/android/tool/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../include/c++/4.9.x/__tree:1819:22: error: the specified comparator type
        does not provide a const call operator [-Werror,-Wuser-defined-warnings]
                       __trigger_diagnostics()), "");
  ```
  My temporary solution is adding ```-Wno-error=user-defined-warnings``` to CMakeLists.txt, turning warning "user-defined-warnings" into a warning even if -Werror is specified.

Here is my modification: https://pastebin.com/E8ZMSnhD
