### ISSUE TITLE
Strings.xml refers to "mixin"

### ISSUE THREAD

**Issue by ordtrogen** [m2049r/xmrwallet#260]
hasn't that been renamed to 'ring size'?

**Comment by m2049r** [comment]
that string is not used.

**Comment by ordtrogen** [comment]
But as a translator, one still comes across it. Will you remove it from strings.xml?

**Comment by m2049r** [comment]
yes, sorry - I need to clear up the resources in general.

**Comment by ordtrogen** [comment]
That sounds promising  :-)   In fact, I have made notes about a number of things in the source strings but haven't had time to write it up.  Possibly next week I could get a review done.

**Comment by m2049r** [comment]
fixed in #266
