### ISSUE TITLE
Stuck in a refreshed loop

### ISSUE THREAD

**Issue by Onefox** [m2049r/xmrwallet#262]
Is there a way to debug the scanning process?

I connected to a testnode and the scanning: 1090036 Blocks remaining doesn't get updated.

In the logcat i see:
04-27 14:41:17.110 12753-978/com.m2049r.xmrwallet.debug D/WalletService$MyWalletL: refreshed()
04-27 14:41:27.625 12753-978/com.m2049r.xmrwallet.debug D/WalletNDK: refreshed
04-27 14:41:27.634 12753-978/com.m2049r.xmrwallet.debug D/WalletService$MyWalletL: refreshed()
04-27 14:41:38.006 12753-978/com.m2049r.xmrwallet.debug D/WalletNDK: refreshed
04-27 14:41:38.016 12753-978/com.m2049r.xmrwallet.debug D/WalletService$MyWalletL: refreshed()

Over and over again.
I build the wallet from master.

**Comment by m2049r** [comment]
On the device there will be a monero-debug folder with the monero core logs. Let me know what you find. Probably the nice is somehow broken. Run your own. Testnodes sync quite fast.

Am 27. April 2018 14:43:00 MESZ schrieb Onefox <notifications@github.com>:

**Comment by Onefox** [comment]
mmh now after I left the wallet open for some time its synced, 
I used my own testnode.

Were is the path for the debug folder within the android/data/com.m2049r.xmrwallet.debug ?

**Comment by m2049r** [comment]
no, its on "external" storage - often, this is ```/sdcard/monero-debug```

**Comment by Onefox** [comment]
The problem is the node, that I am connecting to, as seen in the screenshot.
Both are up to date but the first one on the ubuntu-1604 screen has some forked peers that are ahead.
This is stopping the wallet from syncing.

![image](https://user-images.githubusercontent.com/1709259/39552722-ad0d657e-4e6a-11e8-9de4-f4e2c9eab233.png)

Here is the monero-debug logs:

https://paste.fedoraproject.org/paste/zHx8sYiSmVwPJHfJ5ITeVQ

**Comment by m2049r** [comment]
so you are having the same issue with the official wallet GUI & CLI?

**Comment by Onefox** [comment]
kind of, the official wallet cli at least syncs up to the latest block.
 Its kind of a cross post to:
https://github.com/monero-project/monero/issues/3713

so at the moment i think one of my daemon is kind of behaving strangely... so the monero issue is better of...

**Comment by m2049r** [comment]
i will close this here, because there is nothing we can do about it in monerujo.
