### ISSUE TITLE
Can we generate wallet from Coinomi seed?

### ISSUE THREAD

**Issue by Huge** [m2049r/xmrwallet#273]
I'd like to keep just a single secure phrase for my crypto wallets, but the "Import" feature would not load shorter phrases like 18-word one Coinomi uses. Is there a principial reason to only allow 25-word generator phrases to be imported?

**Comment by jonathancross** [comment]
Monero seeds are unique and must be 25 words.  The seed contains key information not needed by other cryptocurrencies.  Unfortunatly a Coinomi seed will not work.
