### ISSUE TITLE
Stagenet status

### ISSUE THREAD

**Issue by amiuhle** [m2049r/xmrwallet#274]
What's the status for implementing stagenet? Is it in the current pre-release (`1.5.1`) or is there some work left to be done?

**Comment by m2049r** [comment]
it's trivial and when i started doing it and ran a fresh stagenet node it didn't connect to the stagenet network for two hours so i set the task for "later". if you have a hint on how to run a stagenet node please tell me and it will be in the next release. thanks :)

**Comment by amiuhle** [comment]
I just tried and didn't have any problems running a stagenet node at all. Maybe you tried too early and there weren't a lot of nodes yet.

**Comment by m2049r** [comment]
Yes I got it to work. Also have implemented stagenet code. Will PR it next week.

**Comment by m2049r** [comment]
checkout release v1.5.4

**Comment by kim0** [comment]
@m2049r .. sorry couldn't find out how to use stagenet on my Android phone .. I would like to test with stagenet monero. .. Thanks!

**Comment by m2049r** [comment]
no problem @kim0 - download https://github.com/m2049r/xmrwallet/releases/download/v1.10.14/monerujo-1x10x14-stage_universal.apk and enjoy. let me know if you need stagenet xmr - i have lots.

**Comment by kim0** [comment]
@m2049r .. Awesome thank you! Please do send some stagenet XMRs
`54rfFVGh464C91C9jujSne6utu3Xzxgc6MBb9khVfEdYUocQ7ndNQ1EGW38GpRmWYZ9x7WudeGRqQ2Kyg41p8YsWM5ztFjX`

**Comment by kim0** [comment]
@m2049r .. Howdy .. would really love to receive a chunk of those stagenet XMRs. I'm building a tool, and will probably need to send to many people, so it would be great if you can send many XMRs. Thanks!

**Comment by m2049r** [comment]
sorry - i forgot you! sent you 500XMR. let me know if you need more.

**Comment by kim0** [comment]
Thanks! Unfortunately I didn't receive it yet! I double checked the public
key many times. Not sure what went wrong.

Thanks for helping

**Comment by kim0** [comment]
Interesting .. I also received some more coins from a faucet and they were still not showing (balance = 0.0 XMR) .. I restored from seed using cli wallet, and the cli wallet could see all the funds. Seems like some bug at least in stagenet wallet. If you're interested to investigate further, let me know what to do .. Otherwise, I'm good. Thanks for helping

**Comment by m2049r** [comment]
stagenet height calculation is wrong on general. you need to restore from seed using correct height. no matter which client you use.

**Comment by kim0** [comment]
@m2049r .. Thanks. FYI, I restored a new wallet using the seed words. Chosen the data 20190101 which is before any of this happened. Waited a few mins for it to sync. And the newly restored wallet still shows funds as 0.0 XMR
