### ISSUE TITLE
Build Monero

### ISSUE THREAD

**Issue by Pei116** [m2049r/xmrwallet#293]
I'm trying to follow your instructions to build monero project based on Android. https://github.com/m2049r/xmrwallet/blob/master/doc/BUILDING-external-libs.md
But I'm now stuck in this final step of building monero. [And finally: Build Monero](https://github.com/m2049r/xmrwallet/blob/master/doc/BUILDING-external-libs.md#and-finally-build-monero)
What's going on here? I don't see the `/build/build-all-arch.sh` file in any place of monero repositories and that's the issue.
Thanks in any advices.

**Comment by m2049r** [comment]
You need to use my monero fork.

**Comment by Pei116** [comment]
Yep, that's also what I see in the documentation but I can't even find `/build` sub-directory in every branch of that repo.

**Comment by Pei116** [comment]
https://github.com/m2049r/monero. It's your fork right? I can't find that script in this fork as I said.
Would you provide me with that script directly?

**Comment by Pei116** [comment]
I think I've found it but documentation has some missing for it. One needs to specify the correct branch of monero, like `release-v0.12-monerujo`.
`git clone -b release-v0.12-monerujo https://github.com/m2049r/monero.git`

**Comment by m2049r** [comment]
sorry for the late reply! yes, you need to get the correct (latest) branch.
