### ISSUE TITLE
Daemon user name and password

### ISSUE THREAD

**Issue by Engelberg** [m2049r/xmrwallet#294]
Is there a way to specify a daemon user name and password for a Monero node which requires one?

**Comment by Engelberg** [comment]
To clarify, when running a Monero node for personal use, it is common to set up a username and password for the daemon, so that it can't be discovered and connected to by people in general.  The official monero desktop wallet makes it easy to specify the username and password to use when connecting to the daemon.  I would like to be able to do the same with Monujo, so that I can use my own personal node to process transactions.  As far as I can tell, Monujo only allows you to specify ip address and port -- not username and password.  Perhaps I'm missing something and there is a way to embed this information into the connection URL information.  If not, consider this a feature request.

**Comment by crtlib** [comment]
This is already implemented, just specify node's URI as `user:pass@host:port`

**Comment by Engelberg** [comment]
Thank you.  That's exactly what I needed.
