### ISSUE TITLE
Feature request: Allow computation of payment from USD when using xmr.to

### ISSUE THREAD

**Issue by Engelberg** [m2049r/xmrwallet#296]
Currently, the wallet allows you to type in an amount of dollars and compute XMR when sending XMR.  But when sending BTC, it doesn't let you type in the amount of dollars.  Ideally, from dollars you could compute the needed BTC and from BTC you could compute needed XMR.

**Comment by m2049r** [comment]
since we don't have access to a serious/real USD conversion rate, this cannot be done seriously. all in-app fiat conversions are purely indicative and **should not** be used for real transactions!

**Comment by leafcutterant** [comment]
Even that indicative rate would be still better than relying on nothing, and definitely less cumbersome than having to check the price somewhere else and do calculations on your own.

**Comment by leafcutterant** [comment]
How about accessing a serious price source? Or better, let the user opt in and choose a source, or a set of sources which would be averaged by Monerujo?
