### ISSUE TITLE
Fingerprint Sensor not recognized (no fingerprint option)

### ISSUE THREAD

**Issue by toobadsosad** [m2049r/xmrwallet#300]
i just moved my primary phone from LG G5 to Nubia Z17mini

while both phones have fingerprint sensor. i failed to see the option on the Nubia. (no problem with the LG G5, option is available..)

the fingerprint sensor on the Nubia is 100% working as recognized in other apps, as well for unlocking the phone.

PS: the nubia still in Marshmallow, while the LG is Nougat, if it matter.

**Comment by 0140454** [comment]
@toobadsosad 
Hi,
It seems like FingerprintManagerCompact API return wrong value.
This [commit](https://github.com/0140454/xmrwallet/commit/57b79ef572c433b441bf287aed0802594053f4ba) should fix it. Could you try it?

**Comment by m2049r** [comment]
@0140454 can you PR this? or how do I try it out without PR?

**Comment by 0140454** [comment]
@m2049r 
OK, I have created a PR for this issue.

**Comment by toobadsosad** [comment]
yay.. indeed solved.. now fingerprint option is available after i updated. 
thanks 👍

**Comment by Adi168** [comment]
How to integrate FingerprintManagerCompact API to my Nubia Z17 Mini?
I have same problem, help me please.

**Comment by 0140454** [comment]
@Adi168 
This problem is fixed by using FingerprintManager, not FingerprintManagerCompact.
You should check whether ```Build.VERSION.SDK_INT``` is larger or equal to ```Build.VERSION_CODES.M``` first, then get fingerprint service if OS supports it.

**Comment by Adi168** [comment]
Honestly I don't really understand it.
Could you please help me how to check it? 
It happens several times already and i don't know what to do.
Or perhaps you could give me the tutorial step by step?

Thank you.

**Comment by Adi168** [comment]
Hi,

Could you help me please? It happens so many times now and I'm stressed out don't know what to do. I tried to ask some Nubia groups in my country but no one experienced it.

I'm so sorry for disturbing you.
Thank you.

Cheers.

**Comment by m2049r** [comment]
@Adi168 what is it you are trying to do **exactly**?

**Comment by 0140454** [comment]
@Adi168 
Could you describe it in detail?

* What is it you are trying to do
* What is it actually behaves

**Comment by Adi168** [comment]
The fingerprint option just suddenly disappeared. I've tried downgraded and upgraded the ROM, it did work but only for somedays. So I have to re-do it every time the fingerprint sensor doesn't work and the option disappeared. 
I think the fingerprint sensor is not broken, maybe the problem is from the ROM (but I'm not quite sure). 

Some ROM that I've tried are: v. 2.06, v. 2.09, v. 2.10, v. 2.12, v. 2.14 (all global version).

I just know upgrade & downgrade.

**Comment by 0140454** [comment]
@Adi168 
When fingerprint option in monerujo disappeared, could you find fingerprint option in system settings?

If not, I think it should be the issue of ROM. Maybe you can try the latest ROM.
On Nubia website, the latest ROM for Z17 mini is v2.34.

Otherwise, we need to investigate it deeply.
