### ISSUE TITLE
Add an option that lets user can change language manually

### ISSUE THREAD

**Issue by qxxrbull** [m2049r/xmrwallet#310]
When I set my phone's language is Chinese . The xmrwallet display Chinese .
I don't find any option can changed the language to English or other language in App .
I think can add an option that let user can change to others language manually.

**Comment by WorldLanguages** [comment]
Full support for this. My phone is in Spanish but I like crypto apps being in English.

**Comment by M5M400** [comment]
I just came here to request the same thing. Not a fan of those childish German translations :)
