### ISSUE TITLE
Translations for v1.5.5

### ISSUE THREAD

**Issue by m2049r** [m2049r/xmrwallet#315]
@erciccione , the following translations are new in v1.5.5:

```
<string name="accounts_drawer_open">Open Accounts Drawer</string>
<string name="accounts_drawer_close">Close Accounts Drawer</string>
<string name="accounts_drawer_new">Create Account</string>
<string name="accounts_drawer_title">Accounts</string>
<string name="accounts_new">Added new account #%1$d</string>
<string name="tx_account">Account #</string>
<string name="prompt_open_wallet">Opening the wallet&#8230;</string>
<string name="bad_saved_password">Saved password is incorrect.\nPlease enter password manually.</string>
```

All are added to the existing (merged) strings.xml files.

Please have the existing and pending translations updated. Thank you very much!!

If possible, add translations as PRs to the ```translate_v1.5.5``` branch (and not ```master```) so it's all in one place.

**Comment by erciccione** [comment]
Opened new tasks on Taiga asking to update. Regardin the pending pull requests, maybe is better to merge the ready ones and then update them with a new PR. Some are one month old

**Comment by el00ruobuob** [comment]
Done in #316 for French.

**Comment by m2049r** [comment]
yes, @erciccione i will deal with all the pending translations this week.

**Comment by erciccione** [comment]
Opened a reddit post asking for translators: https://www.reddit.com/r/Monero/comments/8rz28r/translations_new_strings_in_monerujo_we_need/

**Comment by BlackLotus64** [comment]
I really remember a discussion here (maybe it was in other place) about the Spanish translation. What happened? Is it done?

**Comment by m2049r** [comment]
superseded by #358
