### ISSUE TITLE
Feature Request: Option to Hide XMR Balance

### ISSUE THREAD

**Issue by Bluecoreg** [m2049r/xmrwallet#326]
Maybe I'm just being paranoid; however, it would be nice to be able to purchase stuff with Monero in a public place without having to cover up my phone screen, worried that someone behind me is able to view my balance.

Instead of having your XMR balance in large and bold text (along with the lastest transactions), maybe have an option to only show the send and receive buttons. There could even possibly be an option to view the wallet balance, but it must also be password protected just like sending XMR is, encase someone snatches your phone after unlocking your account, which has happened to me in the past.

Sort of like you wouldn't want to open your bank's app in public for others to see, I feel the same for the current state of Monerujo.

The app as a whole works great though, thank you all for the hard work you do!

**Comment by m2049r** [comment]
implemented in #458
