### ISSUE TITLE
New option at mnemonic import: number of subaddresses to scan initially

### ISSUE THREAD

**Issue by leafcutterant** [m2049r/xmrwallet#350]
I was seriously impressed by the fact that subaddresses are implemented in Monerujo and how well they work. Awesome job, hands down!

That said, I had some moments where I was not sure what to do or expect, but I think this could be streamlined.

I started to imported a 25-word mnemonic, and while it was scanning, I realized that I need some Nth subaddress's balance. It wasn't obvious whether Monerujo would re-scan the blockchain for those addresses from the restoration height, or only from the present position in the scanning. So I somehow found my way into "Receive" while it was still scanning, and rushed to add the N subaddresses before the sync got to the position when they were first used. Whether because of this or regardless of this, things worked out.

This kind of working introduces ambiguity into the wallet's functioning. It's also inconvenient that you need to go to the Receive screen and then add subaddresses manually to see their already-existing balances.

To improve on this, I propose adding a new option to the mnemonic import screen. It could be called something like "Number of subaddresses to scan initially", and it would automatically derive the N number of subaddresses at the beginning, so that by the time the sync is done, all desired transactions and balances are visible in the wallet. It would save time and effort for the user, and maybe even speed up computations by batching.

Thank you for your work and consideration.

**Comment by m2049r** [comment]
Monerujo scans accounts & subaddresses the same way the offical clients do: 50 accounts & 200 subaddresses each (from the last used respectively) - so there is no user interaction required when restoring wallets. Unless one needs more than 50 UNUSED accounts or 200 UNUSED subaddresses - then maybe the user should use the CLI to restore the wallet and then move that to Monerujo.

Most users are overwhelmed with the "Restore Height" field ... adding a "Subaddress Lookahead" field may not be the right path here.

**Comment by leafcutterant** [comment]
Thank you, I was not familiar with the 50/200 behavior.

I agree that a "Subaddress Lookahead" field would make things more complicated for most users -- and in the light of the above, it's mostly unneeded.

Closing.
