### ISSUE TITLE
Don't scan any past blocks when wallet was generated in Monerujo

### ISSUE THREAD

**Issue by leafcutterant** [m2049r/xmrwallet#351]
Right now it scans from like 25,000 block ago. There's no need for this, as it's guaranteed that no addresses of that wallet existed before the point of creating the wallet.

**Comment by m2049r** [comment]
This is monero core behavior. This is necessary because the blockheight of a newly created wallet is not read from the blockchain, but is calculated. (This is why new stagenet/testnet wallets never work without restoring them with a real blockheight.)
