### ISSUE TITLE
Make it selectable which address to receive to

### ISSUE THREAD

**Issue by leafcutterant** [m2049r/xmrwallet#352]
Right now, you can either receive to your main address, or press the gear button and get the N+1st subaddress, where N is the index of the last generated subaddress, regardless of whether it was used or not. There is no option which address to use for receiving funds.

This is undesirable because
* it prevents you from receiving to the same subaddress more than once (yes, that is desirable in some cases);
* it "wastes" subaddresses which were generated but never received to, while also leaving them in the list of addresses which need to be checked for transactions, thus increasing resource use.

To treat these, I propose that the receiving address be selectable. It could work e.g. by making the address field tappable, which would, upon tapping, launch a scrollable pop-up with a list containing the following: main address, all generated subaddresses this far (plus one if all generated ones have already been received to), and the "generate new subaddress" button (instead of having it on the Receive screen). Such a design should also visually emphasize that the address filed can be tapped and modified.

As an additional idea, I propose that the default receiving address be the M+1st subaddress, where M is the index of the last known (sub)address which received a transaction, or at least has an unconfirmed incoming transaction to it. This achieves an automatic address change and address re-use prevention similar to Electrum.

**Comment by m2049r** [comment]
Subaddresses in Monerujo are meant to be single-shot & disposable. We want to keep it this way for now. If you need more, I suggest you use the GUI or CLI clients.
Resources need for scanning through a couple of unused subaddresses are negligible.
Also, address re-use prevention is not achieved, as you have no idea if an address you have given out will be used in the future.

**Comment by leafcutterant** [comment]
I understand your concerns and the proposed direction. And thanks for clearing up the resource topic.

Let me add a note on why this can be relevant. If you use a wallet both with CLI and Monerujo, transactions received with Monerujo will be invisible to the CLI wallet after a time (unless you keep on generating subaddresses in CLI ad nauseam). In CLI you can keep subaddresses in control, in Monerujo, you can't.

**Comment by SamsungGalaxyPlayer** [comment]
@leafcutterant the default number of subaddresses to scan in the CLI is quite large, no? And if it detects that any are used, it increases the number it scans iirc

**Comment by leafcutterant** [comment]
@SamsungGalaxyPlayer, I believe you are right, it scans 50 accounts and scans until 200 unused subaddresses are found. Could you confirm this? At the time of my last comment I was completely oblivious to this behavior, I thought a subaddress is not scanned for until they are generated in the client. m2049r has just let me know in another issue.

In the light of this, what I proposed has little relevance. Closing.

**Comment by SamsungGalaxyPlayer** [comment]
@leafcutterant correct, I have confirmed these values. As long as a user does not create more than those without receiving any money, then the CLI will work without any additional configuration.
