### ISSUE TITLE
boost/preprocessor/stringize.hpp'file not found

### ISSUE THREAD

**Issue by yagamidev** [m2049r/xmrwallet#355]
Hi,
I run out into that issue when trying to build, how to resolve it ? 

Thanks

**Comment by m2049r** [comment]
did you build boost as per the "Build Boost" section in the doc/BUILDING-external-libs.md?

**Comment by yagamidev** [comment]
Yes I build as described there. But used another version of boost(1.60) cause there was an error saying that the version of boost (1.58) is too old for openSSl

**Comment by m2049r** [comment]
1.58 works perfectly with openssl 1.0.2l - i don't think there is any reason to change the setup.
