### ISSUE TITLE
wallet address contains/displays asian characters

### ISSUE THREAD

**Issue by der-blaue-elefant** [m2049r/xmrwallet#36]
Steps to reproduce:
1. Install App & Open
2. Click on plus in lower right corner
3. Choose wallet name and password
4. Public address contains non-displayable characters (in a test before they had been asian or japanese)
(Environment: Android 6.01, Xiaomi Redmi3, wallet 0.5.3 from APK)

**Comment by der-blaue-elefant** [comment]
![screenshot_2017-09-03-11-16-55-930_com m2049r xmrwallet](https://user-images.githubusercontent.com/25263039/30001823-e026ac34-9099-11e7-9e3c-30fcd14384ed.png)

**Comment by m2049r** [comment]
this happens every time or is sporadic?

EDIT: if you then complete the process and view the wallets details from the wallet list (longpress the wallet and select "Details") is it still broken or does it look fine?
