### ISSUE TITLE
Its not possible to use xmr.to with sweep_all

### ISSUE THREAD

**Issue by Onefox** [m2049r/xmrwallet#367]
This is a feature request.

I would be great if you could also send all to a btc address and the wallet would use xmr.to for that as it already does.
But at the moment there is no way to select all coins from the wallet account.

**Comment by m2049r** [comment]
afaik this is not how xmr.to works. you say how much BTC you want to send; they tell you how much XMR this is. and you send them exactly that amount. there is place for sweep_all in this scenario.

**Comment by Onefox** [comment]
But you could create a bigger order and than do a sweep_all onto that order.
I think this feature would find use cases.

**Comment by m2049r** [comment]
this is just not how the xmr.to integration works. if you make a bigger order, it will just sit there and wait for the rest to come which will never happen. what you want to do is sweep_all to a different account and then pay your BTC normally through xmr.to.
