### ISSUE TITLE
'libunwind.h' file not found

### ISSUE THREAD

**Issue by marceloneil** [m2049r/xmrwallet#369]
I followed the build instructions and included some fixes from #246. Everything seems to work fine (albeit a bit slow) for the arm and arm64 builds. Unfortunately, I get this issue for the x86 build specifically:

```
/opt/android/monero/src/common/stack_trace.cpp:39:10: fatal error: 'libunwind.h' file not found
#include <libunwind.h>
         ^~~~~~~~~~~~~
1 error generated.
make[3]: *** [src/common/CMakeFiles/obj_common.dir/build.make:193: src/common/CMakeFiles/obj_common.dir/stack_trace.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Makefile2:756: src/common/CMakeFiles/obj_common.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
```

I'm not sure why I don't get this issue for arm/arm64. Should I somehow be compiling libunwind for android? Here is my output when I search for `libunwind.h`

```
$ locate libunwind.h
/home/marcel/.android/crystax/sources/cxx-stl/llvm-libc++abi/libcxxabi/include/libunwind.h
/usr/include/libunwind.h
```

**Comment by m2049r** [comment]
don't use libunwind - either uninstall it, or disable it in ```CMakeLists.txt``` (I think commenting out line 368 ```find_package(Libunwind)``` should do the trick)

**Comment by marceloneil** [comment]
Yep, it seems like this is the culprit:
https://github.com/m2049r/monero/blob/2c69c1833119fbfe03030a5fdd92285ca20a6b17/CMakeLists.txt#L357-L376 (which explains why this issue didn't occur for arm)

**Comment by m2049r** [comment]
maybe we should add an ANDROID clause there?

**Comment by marceloneil** [comment]
Possibly, although I'm honestly not sure if that's what caused my issue. I think it hung because of something else
