### ISSUE TITLE
[feature request] Better feedback on connection failure

### ISSUE THREAD

**Issue by jonathancross** [m2049r/xmrwallet#397]
I now have a nice setup using a [connectbot](https://github.com/connectbot/connectbot) ssh tunnel to my remote monero node.
Unfortunatly the connections break after a while.  In this scenario, xmrwallet gives no feedback -- I click on the wallet name, see it change color, but nothing happens.

Would be great to have a message somehow indicating that there was no connection to node, otherwise it may appear that the wallet itself is somehow corrupted / malfunctioning.

**Comment by m2049r** [comment]
are there any steps i can do to reproduce this? when you click on the wallet name it connects to the node to see if it can and reports if it's not reachable. if your connection drops it should not be able to connect and so you should get an error toast. but apparently you don't ...

**Comment by jonathancross** [comment]
Seems that "Notifications" were set to "off" for Monerujo.
Probably "user error" as I may have changed that setting at some point.  Enabling notifications seems to now give me connection feedback.  Sorry for wasting your time.

PS: I am using the setup described here:
https://github.com/jonathancross/jc-docs/blob/master/ssh_tunnel_to_full_node.md
