### ISSUE TITLE
Sync not Saving Progress without Ledger Attached

### ISSUE THREAD

**Issue by russoj88** [m2049r/xmrwallet#399]
I run Monerujo on a Nexus 6P, using a Ledger HW wallet.  Making a wallet without the Ledger, everything seems to sync fine.  Progress is saved each time I close the wallet.

Syncing using the Ledger is not working for me.  It starts syncing, but once I disconnect the Ledger or it times out (auto-lock), the sync progress is lost.  If I start syncing and close the wallet while the Ledger is still attached, the progress is saved.

**Comment by m2049r** [comment]
Yes, you cannot disconnect the ledger while the wallet is open as your keys are on the ledger and they are needed for syncing.

**Comment by russoj88** [comment]
If anyone else has this issue, there's an option on the Ledger to turn off auto-lock.  After that, it took me a few full charges to sync (from 0).

While it's syncing, if I use other apps, and then go back via the "service" notification, it's ok.   If I reopen the app from the home screen, it closes and does not save progress.

**Comment by Mansarde** [comment]
@m2049r Just for clarification, does the auto-lock of the Ledger have the same effect as disconnecting the Ledger (in terms of syncing)?
