### ISSUE TITLE
Question. Is This App Encrypted?

### ISSUE THREAD

**Issue by moneroqxa** [m2049r/xmrwallet#400]
Is all of my data encrypted in the app itself such as private keys, word seeds, etc. Or could another app read my Monerujo app data?

**Comment by SamsungGalaxyPlayer** [comment]
Yes, it is encrypted. Learn more:

https://medium.com/@anhdres/how-monerujos-crazypass-crazy-secure-password-scheme-works-dc4f99a99ff0

https://www.monerujo.io/recources/crazy_secure_passphrase.pdf

Please close this issue if you have no further questions.
