### ISSUE TITLE
Question about placeholder for translation

### ISSUE THREAD

**Issue by apertamono** [m2049r/xmrwallet#421]
Could you explain what's inserted in the following strings from values/strings.xml? Why is the order different for + and -? I tried to find this in the code, but searching for 'Fee' didn't help.

```
+%1$s Fee
- Fee %1$s
```

**Comment by m2049r** [comment]
```+%1$s Fee``` apears on the last screen of the send flow:
```
Succesfully sent
12.34 XMR
+ 0.001123 Fee
```

while ```- Fee %1$s``` appears in the transaction list & transaction info screen underneath the amount sent (which does not include fees):
```
- 12.34 XMR
- Fee 0.001123
```

They should probably both be unified - @baltsar @anhdres ?

**Comment by apertamono** [comment]
OK, thanks for explaining. Either order will work in the Dutch translation.

**Comment by anhdres** [comment]
```
Succesfully sent
12.34 XMR
+ 0.001123 Fee
```
To me looks like you sent 12.34 and 0.001123 was the fee you paid. I would get rid of the + sign so it doesn't appear that you sent the *sum* of both to the receiver.

```
- 12.34 XMR
- Fee 0.001123
```
In this case is clear that both amounts were deducted from your balance.

As they are context sensitive, I don't mind they not being *exactly* the same. If I would have to chose the later (two -) for both screens.
