### ISSUE TITLE
Feature Request: Add ability to rescan blockchain... 

### ISSUE THREAD

**Issue by patoshii** [m2049r/xmrwallet#431]
Currently when you pick the date or block # to start scanning from it will ignore all previous transactions. This is problematic especially if you accidentally put in the wrong block or date. Would be great if there was a "rescan" option starting from a different point of time.

**Comment by m2049r** [comment]
Easy workaround: create a new wallet with the correct height. Adding UI elements for this fringe case is not ideal.

**Comment by m2049r** [comment]
AFAICT rescanning the blockchain is not a good solution in general. The preferred monero solution is to restore from scratch as proposed above.
