### ISSUE TITLE
Feature Request: Add ability to migrate the optional notes to another phone.

### ISSUE THREAD

**Issue by patoshii** [m2049r/xmrwallet#438]
When switching phones, I lose all my optional notes for the transactions I made. 

Maybe provide a way to export these notes for each wallet in a QR code that can be scanned in from the new phone during a phone migration?

**Comment by m2049r** [comment]
When switching phones, you should just copy your ```monerujo``` folder across. Use the "Wallet Files Restore Password" from the wallet details screen to open them there (& then change the passphrase in the wallet details menu to something sensible).

@anhdres This may be a good topic for an article.

**Comment by m2049r** [comment]
@patoshii is the solution above acceptable?

**Comment by patoshii** [comment]
yea i guess. its better than having no way of migrating it. a tutorial would be nice @anhdres

**Comment by anhdres** [comment]
> 
> 
> yea i guess. its better than having no way of migrating it. a tutorial would be nice @anhdres

It's on my todo list!
