### ISSUE TITLE
Node problems

### ISSUE THREAD

**Issue by bigstunta101** [m2049r/xmrwallet#440]
Every node I've tried to use either says "node version incompatible, please upgrade" or "cannot reach node, try another one" 
Can someone please post the latest node so I can use my wallet.

**Comment by SamsungGalaxyPlayer** [comment]
@bigstunta101 this problem will likely only persist for the next week until everyone updates their nodes. Until then, you can try this node:

node.xmrbackb.one:18081

**Comment by m2049r** [comment]
yes, I added a notice in #442 to the latest beta version which explains this a bit & points the user to this thread where we can collect nodes which work until everyone is updated: https://www.reddit.com/r/Monerujo/comments/9n70ys/does_anyone_have_a_list_of_updated_nodes/

**Comment by m2049r** [comment]
@bigstunta101 can we close this?
