### ISSUE TITLE
Monerujo doesn't respond when entering long passwords during wallet creation.

### ISSUE THREAD

**Issue by ghost** [m2049r/xmrwallet#443]
Monerujo Version: 1.8.4 'Bullets And Octane-Pirates'  from F-droid
Resulting Behavior: the app hungs for several seconds to minutes
Expected Behavior: Password is entered in the field 

When I enter a password that is more than 350 characters the app hungs for a long time depending on the length of the password. Is some parallelization needed in Monerujo or is it simply the my processor that can't process the password?

**Comment by m2049r** [comment]
@MSavoritias i am not having ANY issue with this password: `When I enter a password that is more than 350 characters the app hungs for a long time depending on the length of the password. Is some parallelization needed in Monerujo or is it simply the my processor that can't process the password?When I enter a password that is more than 350 characters the app hungs for a long time depending on the length of the password. Is some parallelization needed in Monerujo or is it simply the my processor that can't process the password?`

Both on "create wallet" or opening it - it's just as fast as with a short password. But I am testing on v1.8.4 - could you try that? It's the current version on f-droid.monerujo.io.

**Comment by ghost** [comment]
You are correct it doesn't. My bad for not being more specific. 

Monerujo doesn't respond when you enter a long password in the create wallet screen. As soon as i enter one in wallet passphrase it jungs. Also happens with the lastest version 1.8.4.

**Comment by m2049r** [comment]
as i notes above, the mentioned 472-character password works without any issue - it is processed as fast as a 4-character password. what hardware are you on? what other apps are running in the background?

**Comment by m2049r** [comment]
@MSavoritias please check this with a recent version and respond to my questions above if you are still having issues. thanks.
