### ISSUE TITLE
Opening pre-existing wallet crashes

### ISSUE THREAD

**Issue by billytaylor** [m2049r/xmrwallet#452]
hi

Android 8.0.0 Samsung Galaxy S9
Monerujo 1.8.4 
pre-existing wallet made 1-2 months ago.

So I heard about a recent Monero hard fork etc, so I want to check my XMR. I open monerujo (it has been auto-updated to v1.8.4 recently) for the first time in a while, see I have to use a v9 node, select monero-v9.monerujo.io after some googling, and try to open the wallet.  I get the '0.000000 XMR' and 'Loading wallet...'. 3 secs later it returns to the Wallets screen. If I try to get 'Details' for the wallet, it  goes to the Details screen, says 'Public Address' and the entire app terminates about 2secs later.

I created a 2nd wallet on the same device using 'recover from seed phrase', and it created OK and opens OK. However it shows a 0.00000 XMR balance, which is not expected! Is that not a valid way to try and recover the wallet?

What's the best way to troubleshoot /provide more info please?
thanks for your help

**Comment by m2049r** [comment]
@billytaylor concerning the restored wallet: you probably used a restore height wich was to big. you can also use a date lilke "20180701" for first of july.

concerning the old non-functioning wallet, it may be helpful if you could get a logcat output of the "details" crashing. follow these instructions: https://android.stackexchange.com/questions/33216/how-can-i-get-a-logcat#33217 except for the last step: check there are is no private date in the dump and mail it to me at monerujo.io.

**Comment by billytaylor** [comment]
Wonderful. I don't know if it was a race condition/timing issue which the logcat procedure helped alleviate somehow, but when I tried to get the trace (it took a couple of attempts), it eventually did not crash and loaded the XMR balance for all accounts in the wallet OK. Obviously happy about that. I would suggest either close this now, or see if I can replicate the issue again (when I have some time). Your call. Thanks!

**Comment by m2049r** [comment]
we can close it and reopen if it happens again. maybe check/change the network (wifi/mobile) if it does.
