### ISSUE TITLE
Node connection failed after changing wallet passphrase

### ISSUE THREAD

**Issue by choosoo7** [m2049r/xmrwallet#456]
After successfully changing the passphrase for a monerujo wallet I can no longer open the wallet.
I get this error every time:
> Node connection failed! Check username/password

To reproduce this:
* create new wallet
* open wallet, connecting to node.moneroworld.com:18089
* change wallet passphrase
* exit wallet
* try to open wallet again using new passphrase
* error

I am using version 1.8.4

**Comment by m2049r** [comment]
confirmed: change passphrase renders wallet unusable (Status_Critical)

**Comment by m2049r** [comment]
seems it was a bug in monero v0.13.0.2- upgrade to v0.13.0.4 fixes this.

**Comment by m2049r** [comment]
fixed in https://github.com/m2049r/xmrwallet/releases/tag/v1.9.0 - please test.

**Comment by choosoo7** [comment]
issue is fixed for new wallets, created in 1.9.0, but old wallets are still unusable

**Comment by m2049r** [comment]
but changing the passphrase of old functional wallets works, no?

**Comment by choosoo7** [comment]
I can't test that as I have no old functional wallets.
