### ISSUE TITLE
Cannot connect to Ledger Nano S wallet

### ISSUE THREAD

**Issue by T81** [m2049r/xmrwallet#467]
Attaching the wallet on phone it prompts to open monerujo. Clicking the "+" icon it prompts to restore ledget wallet but when opening monero app in device, it disconnects and no longer recognized from smartphone.

Samsung Galaxy S6 Edge
Android 7.0

**Comment by m2049r** [comment]
see https://www.reddit.com/r/Monero/comments/96g6a5/monerujo_ledger_nano_s_issue/ - maybe something works for you

@cslashm any suggestion/progress/ideas on this issue?

**Comment by m2049r** [comment]
have you tried [this](https://www.reddit.com/r/Monero/comments/96g6a5/monerujo_ledger_nano_s_issue/e4a43ff/) in particular (esp. the order described)?

if that doesn't help, then please (as suggested in the link above) report this issue to [the ledger monero github](https://github.com/LedgerHQ/ledger-app-monero)

**Comment by T81** [comment]
I tried the above suggestions. None of these worked.

**Comment by m2049r** [comment]
even if i were to get a Samsung Galaxy S6 Edge, i don't think i could solve the issue - you need to report this to ledgerwallet. sorry.

**Comment by T81** [comment]
Thanks anyway.
Opened issue here:
https://github.com/LedgerHQ/ledger-app-monero/issues/26
