### ISSUE TITLE
Unable to parse and send to cakewallet QR address 

### ISSUE THREAD

**Issue by mmbyday** [m2049r/xmrwallet#473]
As an example, when using a general QR scanner, the raw QR text scanned from [cakewallet ](https://cakewallet.io/)is in the following format.
monero:4AdkPJoxn7JCvAby9szgnt93MSEwdnxdhaASxbTBm6x5dCwmsDep2UYN4FhStDn5i11nsJbpU7oj59ahg8gXb1Mg3viqCuk?tx_payment_id=&tx_amount=1000000

**Comment by m2049r** [comment]
that is not a valid monero uri - please file an issue with cake wallet. to be more precise: the payment_id may not be empty. it's either there or it's not. when it's there it needs to be set to something valid.

**Comment by mmbyday** [comment]
thanks! issue filed with cakewallet
