### ISSUE TITLE
suggestion: qr scan of payment id

### ISSUE THREAD

**Issue by o5j5vg55bv5hv5j5f8799f9** [m2049r/xmrwallet#492]
payment id can be quite large and it really helps if that's qr-scannable as well

binance, very popular monero exchange, for example does 64 char long payment id but shows qr code that the app can't scan.

thanks!

**Comment by m2049r** [comment]
payment_id is used when scanning - can you pls mail me a sample qr code which doesnt work?

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
Binance has 2 separate qr codes for xmr. 1 for address. 1 for payment id. 

Payment id was not included in address qr.

I guess that's not standard.

Try depositing any xmr into binance to see.

**Comment by m2049r** [comment]
if binance is doing it wrong, you may want to submit a ticket there for them to implement the correct URI scheme for monero transactions which is documented here: https://github.com/monero-project/monero/wiki/URI-Formatting
