### ISSUE TITLE
seed for subaddresses?

### ISSUE THREAD

**Issue by marco4444** [m2049r/xmrwallet#498]
Had 2 addresses in my (crashed) monerujo.
Imported the seed into monero-wallet-cli which only loaded the funds of the primary address.
My question:
Is the seed only protecting one of the monerujo Monero addresses?

Issue with my monerujo app is that it crashs after about 20 seconds always when starting. Happens since the recent update.

**Comment by m2049r** [comment]
are you sure you used the correct restore height when restoring the wallet? subaddresses get scanned automatically - on the CLI i think looking forward 300 subaddresses.

about the crashing - do you think you can provide an adb logcat (maybe by mail)? check out https://www.xda-developers.com/guide-sending-a-logcat-to-help-debug-your-favorite-app/ for a guide

**Comment by marco4444** [comment]
Worked now to secure funds, thanks for your help!
Read in other channel that I'm the only one with the problem, so I guess it's not worth to spend investigation time for an old android version on an old phone.
Going t re-install the app.
