### ISSUE TITLE
No Payment ID 

### ISSUE THREAD

**Issue by Lisergiko** [m2049r/xmrwallet#500]
I am a total ignorant when it comes to programming and decentralized systems. I am really thankful for your work and I'm sorry to waste your time and effort with such an issue. 

I know that Payment IDs are becoming obsolete and that we use Integrated Addresses now, but I need a payment ID to withdraw my funds from Binance. They kicked me out after updating the Term of Use and I need to withdraw my funds as soon as possible, before they seize everything and delete my account. They don't support Integrated Addresses and are asking for Payment ID. 

I'll be shifting to Kraken but they only use Integrated Addresses. So I'll need to transfer everything to my Monerujo wallet, but I can't find the Payment ID anywhere. I contacted Binance support and the useless bot that responded said that I must not copy an Integrated Address in the address space because my funds will be lost, and then told me to write Address and Payment ID separately. 

I don't know what to do. It'd be great to have the option of choosing Simple Address & Payment ID or just the Integrated Address. 

Even if I decide to open and sync the Monero GUI, I fear my computer might crash. That is why I haven't synced it in months. The same type of crash happens when using Adobe products...

**Comment by m2049r** [comment]
Usually there is no need for a payment id when WITHDRAWING funds (but i don't know binance). If they need one you can give them one: The payment id is just a random sequence of 16 hexadecimal characters (i.e. letters a-f and digits 0-9) like "0123456789abcdef" which is a valid payment id or "fabcedafbc65de34". It's basically irrelevant in your use case. You will see it with the incoming transaction.

**Comment by jompigrande** [comment]
Hello im trying to deposit to cryptopia address as i always do, scanning QR code, but its using 40 charactes long payment ID, app its telling its not valid LOKI address, i also tried manually adding the info, but payment addres shows 40/16 in red, so i dont want to issue it and be at risk to fail!

**Comment by m2049r** [comment]
well, payment ids cannot be 40 characters. either 16 or 64.

also, this repo here is for monerujo - which is the MONERO wallet. not LOKI. please submit your issue to https://github.com/loki-project/loki-android-wallet
