### ISSUE TITLE
[Bug] Transaction amount shown in Street Mode confirm screen for entire balance

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [m2049r/xmrwallet#504]
Bug: Users can learn the full balance of an account in street mode.

Steps to replicate:

1. Enter street mode

2. Press "give" to initiate transaction send process

3. Add address (I used getmonero.org)

4. Balance properly shows "???". Click the infinity symbol in the upper right

5. In confirmation screen, total sent amount is shown.

Desired behavior in step 5 (confirmation screen):

* Show actual fee

* Show "Amount hidden" for amount

* Show "Entire confirmed balance" for TOTAL. If too long, use "Entire balance"

**Comment by m2049r** [comment]
implemented in #526
