### ISSUE TITLE
Street Mode show received transactions

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [m2049r/xmrwallet#505]
There should be a configurable option to show received transactions using Street Mode. These should be dismissable.

Example image below:

![image](https://user-images.githubusercontent.com/12520755/50492460-62b59300-09dd-11e9-95c8-7988f8084aac.png)

Clicking on the X hides the transaction from Street Mode.

Note: they only appear if the transaction is to the current active address.

Configurable options:

1. Street Mode notifications: on or off toggle (default on)

The following are disabled when #1 is toggled off, available when toggled on

2. Display amount: dropdown for currency type (off, XMR, USD, EUR, BTC, etc) (default off)

I don't think it's necessary to display the account name (it's already active). I also don't think any users find it necessary to disable the time.

**Comment by m2049r** [comment]
how about we just add a swipe-to-dsmiss function for transactions when in streetmode?

**Comment by m2049r** [comment]
i think this is solved with #514
