### ISSUE TITLE
Migrate Localization management to a localization platform

### ISSUE THREAD

**Issue by erciccione** [m2049r/xmrwallet#521]
Opening this issue to keep track of the migration of all translation related work from this repository to the translation platform [Pootle](https://translate.getmonero.org)

@m2049r Please contact me so we can start

**Comment by erciccione** [comment]
@m2049r pinged you on matrix

**Comment by erciccione** [comment]
I found a quick way to translate .xml files on Pootle. Leaving this in standby at the moment since i starte to test another platform: Weblate, which would make the integration with Monerujo easier.

(See monero-ecosystem/monero-translations#51)

**Comment by erciccione** [comment]
An update on Weblate:
The initial integration with weblate looks very good. Only few tweaks needed to the way checks are handled, since at the moment if a string is found in english in the language file, weblate will complain (these strings were called *Fuzzy* in Pootle). 

Anyway everything should work flawlessy for all the files we need translated: `strings.xml`, `about.xml` and `help.xml`

![weblate-projects](https://user-images.githubusercontent.com/28106476/57642500-c5d44a80-75b7-11e9-8447-1f697613ec7c.png)

**Comment by erciccione** [comment]
@m2049r asking you also here hoping to have an answer soon, since i want to start the migration as soon as the new Monero release is out:

Would be possible to have the missing translated strings in the language files not in english, but just empty (please check my comment above)?

This way Weblate won't catch them as "same as source text" and mark them as "need work". It would be quite bad UX otherwise, since all strings will show always ~99% complete, when it's not the case.

**Comment by erciccione** [comment]
Pinging you here and by PM @m2049r. I really need an answer, this issue has been stalling for months and i never got an answer back to my last PM.

**Comment by m2049r** [comment]
we need the missing strings as english - otherwise the non-translated stuff will be empty in the app.

**Comment by erciccione** [comment]
Is there a way to automatically pull the english version if there is no translation? with the current system, monerujo on weblate will result very confusing for translators (see screenshot above).

**Comment by m2049r** [comment]
the english version is automatically pulled (in the app at runtime) if there is no translation. this results in tests failing (missing translation) - but this can be turned off.

**Comment by erciccione** [comment]
Disabling the checks will make it i guess.

After that is only necessary to remove the untranslated strings in the language files, so that they will show correctly on weblate. Do you have an automatic way to do this? if not, no problem, i can do it manually. Just let me know so i can start.

**Comment by erciccione** [comment]
Weblate is almost ready and will be operative soon, **Monerujo will not be translatable on the platform**.

As said in the comments above, the present configuration of the language files is not compatible with Weblate and i'm not going to beg for answers anymore, especially since including Monerujo on Weblate requires a lot of work on my side and this integration would be given *for free* to the Monerujo team, which as can be seen from my messages on this thread and the extreme pain i went through even just to get an answer on the Monerujo chat, doesn't look interested in this integration.

**Comment by erciccione** [comment]
>What's with the drama? I have not seen weblate. Judging from your comments it's not compatible with android stuff (disabling checks or manual conversions are not viable long-term). And we have been contributing to your FFS. Are you saying that you are dropping monerujo translations altogether?

This is a message posted by @m2049r on `#monero-translations`. I'm answering here to keep the records and because it's a better format than a chat.

> What's with the drama?

No drama at all, i'm acknowledging that the Monerujo team is not making the efforts necessary to be integrated into Weblate.

> Judging from your comments it's not compatible with android stuff (disabling checks or manual conversions are not viable long-term)

Weblate is used for many android apps, it just needs to be tweaked. You are saying only now that in your opinion disabling checks is not viable long term. As can be seen from my comments above, i've been asking for an answer (any answer) for quite some time.

> And we have been contributing to your FFS

Since you are pointing this out let me clarify 2 things: 
1. This integration is not part of the FFS that monerujo supported (and even if it did, that's not how FFS works). Monerujo was tested on my local weblate instance, as for my CCS proposal, but as i pointed out in the comments some tweaks are needed to make the integration possible.
2. (AFAIK) Monerujo contributed only to my last proposal, which funded me for 3 months of work, but has benefited of my work (and the translators of the Monero Localization Workgroup) for almost 2 years, so i really don't see the relevance of saying "we have been contributing to your FFS".

> Are you saying that you are dropping monerujo translations altogether?

I'm not the coordinator of the Localization Workgroup anymore, so i cannot drop something that is not my responsability. I'm not funded to deal with localizations anymore ([this is the announcement](https://old.reddit.com/r/Monero/comments/c06vuw/my_last_proposal_as_coordinator_of_the/)). The work i'm doing on weblate will be in another CCS proposal, which i haven't created yet.

I want to clarify again that, beside the fact that has been a pain to coordinate with the team (this GitHub issue is a good example, but another one would be when i *found out* (enphasis on 'found out', even if i worked on Monerujo for long time, apparently nobody though was necessary to let me know there are meetings) of the existence of Monerujo team meetings, i asked to participate and that they happen in public, both requests were ignored) i have nothing against Monerujo. I pointed out the problems that disallow the app to be on Weblate in this state of things.

Since i have enough of continuously pinging the team asking to resolve problems they should be interested in resolving in the first place, i'm just communicating the impossibility to complete the integration until the technical problems will be solved.

**Comment by m2049r** [comment]
ok @erciccione. if you want to contribute, please tell us what "tweaks" need to be done that so many other android apps have done to be on weblate. and we can put them on the backlog. if not, i guess that's fine as well, and a shame.

i would like to point out, that you have not been ignored. we are three people who have real jobs and families which already take more than 100% of our time. out of these three, only i can do technical stuff. i hope you understand it's not a lack of interest or something personal against you - it's a lack of time.

> including Monerujo on Weblate requires a lot of work on my side and this integration would be given *for free* to the Monerujo team

everyone working on monerujo (including the core team) is working *for free* - not just you.

> existence of Monerujo team meetings

of course there are meetings. these are not public and are between the three members of the core team only where we discuss future design & development. the monerujo tasks are public on taiga.

**Comment by erciccione** [comment]
> tell us what "tweaks" need to be done that so many other android apps have done to be on weblate

Please see [this](https://github.com/m2049r/xmrwallet/issues/521#issuecomment-491921289) and [this](https://github.com/m2049r/xmrwallet/issues/521#issuecomment-497752853) comment. You may also want to take a look at the [supported file formats](https://docs.weblate.org/en/latest/formats.html). Examples of android apps worked on weblate: [F-Droid](), [openScale](https://hosted.weblate.org/projects/openscale/#languages), [wallabag](https://hosted.weblate.org/projects/wallabag/android-app/fr/0). I found these after a very quick google search, i'm sure there are many more.

In few words: the value ofthe untranslated strings in the language files must be empty or weblate won't be able to recognize them as translatable.

Contact me if you need support and i will be happy to help.
