### ISSUE TITLE
Password input field no longer selected

### ISSUE THREAD

**Issue by Forage** [m2049r/xmrwallet#565]
Hi,

Since one or two releases the password dialog input field when opening a wallet is no longer automatically selected/active. You now have to tap it manually first before the on-screen keyboard appears.

This is making me loose 'a lot of time' and starting to hurt my finger 😜

Using version 1.11.5 on Android 9.

Let me know if you need any more details.

**Comment by m2049r** [comment]
is this still the case for you with most recent version?

**Comment by Forage** [comment]
Indeed no, at least 1.11.13 does not show this issue any longer. Thanks for the correction.
