### ISSUE TITLE
[Feature Request] Add to f-droid repository

### ISSUE THREAD

**Issue by m2049r** [m2049r/xmrwallet#57]

**Comment by PC-Admin** [comment]
Yes please! the more wallets on FDroid the better, this would be the first XMR wallet to reach FDroid.

**Comment by m2049r** [comment]
i am having a hard time setting up an f-droid build environment up on a ubuntu server. so if anyone knows how to do it ...

**Comment by golere** [comment]
I think it's also possible to open an issue here:
https://gitlab.com/fdroid/rfp/issues
(Explanation here: https://f-droid.org/wiki/page/Inclusion_How-To#Proposal_by_Submission_Queue )

This is the template for the issue:

* [ ] The app complies with the [inclusion citeria](https://f-droid.org/wiki/page/Inclusion_Policy)
* [ ] The app is not already listed in the repo or issue tracker.
* [ ] The original app author has been notified (and supports the inclusion).

---------------------

### Link to the source code:
### Link to app in another app store:
### License used:
### Category:
### Summary:
### Description:

**Comment by m2049r** [comment]
thanks

**Comment by PC-Admin** [comment]
I greatly appreciate all the work that's being done on this. I look forward to casually offering the people around me XMR payments from my phone.

**Comment by gjedeer** [comment]
@m2049r i've set up f-droid dev environment a couple of times, i can help you set up or give you access to a vps with fdroid-server preinstalled. Email me if you just need help setting it up on your own hardware.

**Comment by xmr-karnal** [comment]
For those of us who prefer not to run google services on our devices, would it be possible to [include this app on f-droid](https://f-droid.org/en/docs/Inclusion_How-To) ?

I might also add that as far as I can see, the sort of user who goes through the trouble of learning how to install a custom rom without google services/apps on their device, is at this point probably also interested in cryptocurrency - publishing the app on [f-droid](https://f-droid.org) to hordes of foss fans seems like a good way to get some exposition with the right crowd!

**Comment by faissaloo** [comment]
I'm suprised it's still not on fdroid, I don't really want to have to use Yalp to install & mamage upgrades for something that could be added to fdroid perfectly fine...

**Comment by xmr-karnal** [comment]
@m2049r what is currently preventing the app from being added on f-droid?

There still aren't that many cryptocurrency wallets available there, most of the ones that are on f-droid are outdated/unmaintained, this is a clear opportunity to give monero/monerujo exposure with a crowd that by default should be interested in it.

**Comment by gjedeer** [comment]
@karnal It's hard to build xmrwallet entirely from source. I once spent an afternoon trying to make an f-droid build file for it but an afternoon wasn't enough for this task. It builds the whole Monero daemon, the easily buildable Java part is just a small part of this app.

**Comment by jenniferberger** [comment]
https://f-droid.monerujo.io/ contains a working build with version 1.4.7 from 2018-04-15
i went to this ticket to find it mentioned (and confirming that the repo is a valid source) but no comments on that - please add the signature here.
Not sure if the f-droid main repository is really required.

**Comment by m2049r** [comment]
it's in the ```README.md``` (second bullet in quickstart) - mabye it should be more prominent - where would it be better?

**Comment by pille** [comment]
@m2049r what's the reason for having a seperate repo, instead of having it included in the main f-droid repo?

**Comment by m2049r** [comment]
@pille 

1) because i have not managed to get a buildscript running according to f-droid guidelines

2) having an own repo is in the spirit of decentralization which is also in the spirit of f-droid and gives me more control of when, what and how stuff is in there.

**Comment by chpio** [comment]
the fdroid repo is broken, invalid ssl cert / 404

**Comment by jluttine** [comment]
Are there any plans to bring Monerujo to the F-Droid official repository anymore? If someone would like to work on the build script for F-Droid, do you have any pointers on what has been done/tried, what were the issues and how one could try to solve those?

**Comment by maltfield** [comment]
Currently looking for a monero wallet on android, and came across this thread.

I also checked-out MyMonero's thread on adding to f-droid here

 * https://github.com/mymonero/mymonero-mobile/issues/23

I'm not an expert, but from what I gather MyMonero couldn't be put on fdroid because it included blacklisted software (firebase, google services, etc).

This begs the question: was Monerujo put in a custom repo so they could bypass these blacklists? Should the community be concerned about non-free contents of Monerujo because it's not in the main repo?

I understand the argument for decentralization, but a custom repo does raise some eyebrows.

**Comment by ramioimar** [comment]
> This begs the question: was Monerujo put in a custom repo so they could bypass these blacklists? Should the community be concerned about non-free contents of Monerujo because it's not in the main repo?
> 
> I understand the argument for decentralization, but a custom repo does raise some eyebrows.

Being in the main ffdroid repository is the gold standard for any software that claims to be private. Monerujo inspires a certain amount of trust because the project is open source. But the fdroid issue should not cause doubts, but confidence that the project is not all right in fundamental things.
This is one of the main values of fdroid, that it allows you to weed out questionable projects.

**Comment by maltfield** [comment]
> Being in the main ffdroid repository is the gold standard for any software that claims to be private. Monerujo inspires a certain amount of trust because the project is open source. But the fdroid issue should not cause doubts, but confidence that the project is not all right in fundamental things. This is one of the main values of fdroid, that it allows you to weed out questionable projects.

Yes, I agree that being in the official fdroid repository inspires great confidence.

My point is that this is *not* in fdroid's official repository. It's in a custom repository -- which I suspect means it's no longer requiring the package to meet the same "gold standard".

**Comment by ramioimar** [comment]
> Yes, I agree that being in the official fdroid repository inspires great confidence.
> 
> My point is that this is _not_ in fdroid's official repository. It's in a custom repository -- which I suspect means it's no longer requiring the package to meet the same "gold standard".

Yeah, I agree. It could be anything inside. Named as fdroid, but not really part of the fdroid repository.

**Comment by xuhcc** [comment]
F-Droid can even distribute APKs signed by developers: https://f-droid.org/en/2023/09/03/reproducible-builds-signing-keys-and-binary-repos.html

Custom repo can still be used, and people can rely on it in an unlikely case of F-Droid removing Monerujo.

#232

**Comment by RasheedAZ** [comment]
Any update on this? Thanks.

Currently there appears to be no Monero wallets on F-Droid :(

**Comment by kusyka911** [comment]
@m2049r I agree with other comments. For better reputation it's good for the app to be present in main f-droid repo. It's been years since your last update on this question. Of course custom repo is not so bad, but combined with play protect warning #920 it looks suspicious. Please try to make it to main f-droid repo.

**Comment by licaon-kter** [comment]
https://github.com/m2049r/xmrwallet/releases/tag/v4.1.5 -> commit `989d52b33de200253f1ea3bc2d7d91b8764079fd`

download APK, unpack, `grep revision META-INF/version-control-info.textproto` -> `revision: "b08cd2fd2f18af55b0f1ee5003a88d8e81712e06"`

https://github.com/m2049r/xmrwallet/commit/b08cd2fd2f18af55b0f1ee5003a88d8e81712e06 -> 404

so much FOSS :(

**Comment by ramioimar** [comment]
> https://github.com/m2049r/xmrwallet/releases/tag/v4.1.5 -> commit `989d52b33de200253f1ea3bc2d7d91b8764079fd`
> 
> download APK, unpack, `grep revision META-INF/version-control-info.textproto` -> `revision: "b08cd2fd2f18af55b0f1ee5003a88d8e81712e06"`
> 
> [b08cd2f](https://github.com/m2049r/xmrwallet/commit/b08cd2fd2f18af55b0f1ee5003a88d8e81712e06) -> 404
> 
> so much FOSS :(

Thank you for sharing the results of your research.
As I [mentioned earlier](https://github.com/m2049r/xmrwallet/issues/57#issuecomment-1704073540), there are good reasons not to trust the Monerujo project 
Personally, I would not recommend using it at least for the main wallet.
