### ISSUE TITLE
Accept Monero addresses that contain spaces, line breaks

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [m2049r/xmrwallet#578]
Sometimes I paste a Monero address in the receiver field that contains a random space somewhere or a new line. I then need to go through and figure out where it is.

Ideally, Monerujo can remove these spaces and new lines from the address to check if it is valid. Common examples include ignoring the last space after an address, or a line break that occurs when copying addresses that continue for multiple lines on a document.

**Comment by skorokithakis** [comment]
This is a good improvement for usability.

**Comment by m2049r** [comment]
yes.

**Comment by m2049r** [comment]
implemented in #592 (paste button which also does this)
