### ISSUE TITLE
Monerujo keeps resyncing from scratch every time with Ledger

### ISSUE THREAD

**Issue by skorokithakis** [m2049r/xmrwallet#579]
I have a Ledger wallet, and whenever I open my wallet it starts rescanning 200k+ blocks. Even if I close the wallet now, wait for it to close, and reopen right away, Monerujo will take half an hour rescanning a bunch of blocks.

**Comment by m2049r** [comment]
can you try to create a new wallet and use a different node? does this happen again?

**Comment by skorokithakis** [comment]
It actually stopped happening after two or three times and I didn't notice it again, let me check now.

**Comment by skorokithakis** [comment]
Yes, it works fine now. Do you think it was the node?

**Comment by m2049r** [comment]
yes, i think it was the node. thanks for retesting!
