### ISSUE TITLE
[Proposal] Create a GitHub organization for Monerujo

### ISSUE THREAD

**Issue by erciccione** [m2049r/xmrwallet#582]
@m2049r What about creating a dedicated organization for Monerujo on Github and transfer this repo there?

Right now there are some repositories on your personal account that i didn't even know existed before today. I think would be much more organized to have an organization called *Monerujo* cointaining This repository, monerujo-hw and monerujo-site.

This would also make participation from members of the community easier. Since you, as administrator, could add members to the project, who could help with managing issues and projects. Subprojects could be created to track the workflow and much more. I think it would make a lot easier for interested developers to chime in, since at the moment external contributions beside translations are basically non-existent. Basically, it would help to create an actual community around monerujo, a bist like it's happening with the main Monero wallets. 

i would personally be happy to help manage the organizative side. What do you think?

**Comment by m2049r** [comment]
is there a down side?

**Comment by erciccione** [comment]
No downsides. Except changing links to the new repository, but i wouldn;t call that a downside :P

**Comment by m2049r** [comment]
let's do it then. maybe you can assist me?

**Comment by erciccione** [comment]
Sure. I see there is already a project called Monerujo: https://github.com/monerujo
If somebody from the Monerujo team created it, the repositories could be transferred direclty there.

(I'm now on the "Monerujo public room" on MatterMost. We can live chat there if you prefer)
