### ISSUE TITLE
Show used Open Source Licenses

### ISSUE THREAD

**Issue by BenedictP** [m2049r/xmrwallet#59]
There should be a possibility to show which Open Source Licenses the Apps uses.

To automate this it's possible to use: https://github.com/mikepenz/AboutLibraries/

**Comment by m2049r** [comment]
The AboutLibraries is pretty cool - but it adds 1MB to a 6MB APK.

Used https://github.com/adamsp/AndroidLicensesPage instead which is not as pretty but has negligible effect on APK size and gets the job done nonetheless.

**Comment by m2049r** [comment]
argh - forgot the monero licenses

**Comment by BenedictP** [comment]
> The AboutLibraries is pretty cool - but it adds 1MB to a 6MB APK.

With or withour ProGuard activated?

**Comment by m2049r** [comment]
without. read the discussion about proguard on AboutLibraries. saw that most of the licenses and libraries are not included. and decided it would be easier and faster to make a simple dialog instead.
