### ISSUE TITLE
Zenfone 2 apk question

### ISSUE THREAD

**Issue by watertim** [m2049r/xmrwallet#618]
Hello, I want to use this app in my Zenfone 2.
You also said that "Users of Zenfone MAX & Zenfone 2 Laser (possibly others) MUST use the armeabi-v7a APK".
However, I find none of apk which is for armeabi-v7a devices.
Should I build it by myself or can you provide it?

Please excuse my poor English.

**Comment by m2049r** [comment]
good point! i will provide that variant as part of the releases. just added it to https://github.com/m2049r/xmrwallet/releases/tag/v1.11.13
