### ISSUE TITLE
Linux Version?

### ISSUE THREAD

**Issue by trymeouteh** [m2049r/xmrwallet#619]
This app is amazing and I love it. Will it be possible to create a Linux version for mobile phones that runs linux such as the Librem 5 and Ubuntu Touch devices. 

I know it is a big task but I the foss community would love it! Especially since they can use xmr.to within the app and not needing to go to the website.

**Comment by m2049r** [comment]
it's a fantastic idea, but at the momemt it's not possible since it's very very android specific.
