### ISSUE TITLE
My wallet is empty!

### ISSUE THREAD

**Issue by WiilliamWollas** [m2049r/xmrwallet#622]
Dear friends, I sent 0,4 Monero on my wallet but it is empty.
This is my information:

Freewallet Transaction
Transfer
Request ID: a28aff80-6d0e-67e6-b28e-efce8d624315
Amount: 0.4 XMR
Transaction fee: 0.0001  XMR
Status: is completed

I not understand!!! Can someone help me?

Thanks for all

**Comment by m2049r** [comment]
Make sure your wallet is synced (check the block number next to "Synced" in the open wallet under the balance and compare it to e.g. xmrchain.net. If it's off, find & use a node which is up to date (don't worry if it's just off by 1).

If you are synced, the usual procedure when you don't receive funds is to request proof of sending. This involves getting the "tx hash" and the "tx private key" fro the sending party. You can then verify they actually transferred funds using this data with the official monero client or on (for example) xmrchain.net by finding & opening the transaction (with the tx hash) & entering the tx private key & your receiving address in the "prove sending" tab there.

If the funds were not received & the wallet is synced, in 10/10 cases the funds were not sent.

**Comment by WiilliamWollas** [comment]
I did the test and tried other nodes too but the wallet is always empty. I checked on the xmrchain.net site with the hash and the transaction is ok. I do not know what to think.

**Comment by m2049r** [comment]
please mail me the hashes and all other data to help at monerujo dot io.

**Comment by WiilliamWollas** [comment]
Freewallet Transaction

Transfer
Request ID: a28aff80-6d0e-67e6-b28e-efce8d624315

Amount: 0.4 XMR

Transaction fee: 0.0001  XMR

Wallet address:
42ZpYxXHqMFPzbsdz4ASAgXq37xm6wJtV1LNiNxLfYepKCido2UKdn65AYVhkF8vcE3tdy3E79t2ya68sxcSc5cePnqbRcu

Hash:
33b33dd94ad861b8014eae6f6d53c867cbba773d64981efabf6fe65c739cb248

Date: September 6 2019

Thanks

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by m2049r** [comment]
how did you check this transaction without the transaction private key?

for all you know, the transaction could be 78e1037432ad692032f45960ec06423cfcf247137d829b05a440f17001f041d1 or none at all!

btw: not a good idea to post you private info on github!

**Comment by WiilliamWollas** [comment]
I not understand. I have used an app Monero and send my Monero  with new adress and stop. The other app Ask me only new address. I am an stupid because not understand.

**Comment by m2049r** [comment]
you need to get the "transaction private key" from freewallet.

**Comment by WiilliamWollas** [comment]
Hi Friend, on freewallet give me that transition Is expired 😭

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by m2049r** [comment]
Transactions do not "expire" - please check the warnings against using freewallet on the official Monero subreddit here: https://www.reddit.com/r/Monero/wiki/avoid

**Comment by WiilliamWollas** [comment]
Dear friend, this Is the screenshot on freewallet:

[Image]



Ottieni Outlook per Android<https://aka.ms/ghei36>
________________________________
