### ISSUE TITLE
25 word seed

### ISSUE THREAD

**Issue by maikelmclauflin** [m2049r/xmrwallet#627]
setting up a new wallet. first time opening app. wrote down my seed. noticed that the last word was repeated. thought it was odd. counted the words, ended up with 25 instead of 24. kind of confusing

**Comment by pricead** [comment]
Monero seeds are 25 words, not 24. Repeated words are not uncommon either.

**Comment by maikelmclauflin** [comment]
alright. cool. good to know

**Comment by m2049r** [comment]
the last word is *always* one of the other words.
