### ISSUE TITLE
monerujo fails to connect to node running monero v0.15.0.0

### ISSUE THREAD

**Issue by lilyanatia** [m2049r/xmrwallet#629]
just says "Node version incompatible - please upgrade!"

**Comment by leonardochaia** [comment]
Indeed its happening.
I was checking out the code but I'm not sure where the required version number is specified.

**Comment by lilyanatia** [comment]
it seems to be working now on the latest beta version.

**Comment by ghost** [comment]
@hotaru2k3 Can you link the beta release?

**Comment by lilyanatia** [comment]
@mathsw https://github.com/m2049r/xmrwallet/releases/tag/v1.12.3
