### ISSUE TITLE
Connecting to testnet node fails

### ISSUE THREAD

**Issue by fullmetalScience** [m2049r/xmrwallet#650]
When adding a testnet node, pressing the "Test" button has ping and IP confirm correctly, but height displays as `0 (v0)` even though the node itself is synced to the correct block height.

After clicking "OK", the node shows up in the list, but below its name it says *"Connection error"* or sometimes *"Connection error 200"*. The "wifi" icon to the right is struck out.

Tried both, public and private testnets;

**Comment by ask6155** [comment]
Can confirm, same error also happens on stagenet nodes

**Comment by m2049r** [comment]
there is no testnet version prebuilt. either build it yourself or use the stagenet version in the release downloads here.
