### ISSUE TITLE
"Invalid Monero Address" when scanning integrated address on testnet

### ISSUE THREAD

**Issue by amiuhle** [m2049r/xmrwallet#67]
I'm getting an "Invalid Monero Address" error message when scanning an integrated address on testnet.  
No idea whether it's because of testnet, or integrated address, or the combination of both.

Sample barcode (just enter an amount, all other inputs are optional):  
https://amiuhle.github.io/kasisto

Edit: It has a `tx_amount` URL parameter, which is the "official" way to encode an amount.

**Comment by m2049r** [comment]
actually, i think this is a bug in kasisto as the qr code it generates is not to [spec](https://github.com/monero-project/monero/wiki/URI-Formatting). Submitted [an issue](https://github.com/amiuhle/kasisto/issues/20) with them.

**Comment by m2049r** [comment]
nevertheless i need to implement handling of manually entered (and copy/pasted) integrated addresses.

**Comment by amiuhle** [comment]
You're right, thanks.

I didn't even know this spec existed!
