### ISSUE TITLE
Use of a colon in tx_description crashes Monerujo

### ISSUE THREAD

**Issue by Cactii1** [m2049r/xmrwallet#685]
Using a colon in the tx_description field in the QR Code crashes Monerujo. It closes the wallet and seems to drop connection from other nodes after scanning a QR Code that includes a colon in the field.

**Comment by dscotese** [comment]
I wanted to test this issue in the last version I installed (10/18/2020).  I cannot find a version number in the app.
I made a qr code with a single colon in it. In this case, the app ignores the QR code.
I found the following string at https://monerodocs.org/interacting/monero-wallet-rpc-reference/ and tried it:
`monero:55LTR8KniP4LQGJSPtbYDacR7dz8RBFnsfAKMaMuwUNYX6aQbBcovzDPyrQF9KXF9tVU6Xk3K8no1BywnJX6GvZX8yJsXvt?tx_payment_id=420fa29b2d9a49f5&tx_amount=0.000000000010&recipient_name=el00ruobuob%20Stagenet%20wallet&tx_description=Testing%20out%20the%20make_uri%20function.`
This has a colon in it (but not in the description field) and it scans fine and returns "Not a valid payment URI." though it seems valid to me.

This URI works: `monero:4CaLQAveWB1YzzhX4Z8EVDKzeCjkXMejH6CrccFuu1BKQxJ1pbDxr8W6YqrKh3jYWccJjnFkYRPgiWWk5WR8erLG8Y7At2dKAAGJ3RVcmB?tx_description=Testing` but this one doesn't: `monero:4CaLQAveWB1YzzhX4Z8EVDKzeCjkXMejH6CrccFuu1BKQxJ1pbDxr8W6YqrKh3jYWccJjnFkYRPgiWWk5WR8erLG8Y7At2dKAAGJ3RVcmB?tx_description=Testing:` and this one does: `monero:4CaLQAveWB1YzzhX4Z8EVDKzeCjkXMejH6CrccFuu1BKQxJ1pbDxr8W6YqrKh3jYWccJjnFkYRPgiWWk5WR8erLG8Y7At2dKAAGJ3RVcmB?tx_description=Testing%3A` - You have to encode the colon to avoid crashing the app.  You can use upper or lower case hex digits in the HTMLEntity.

The bug, therefore, is probably a mismatch between how uri.getEncodedQuery handles a colon in a querystring (probably throwing an exception) and how Monerujo handles it.  This is at xmrwallet/data/BarcodeData.java on line 162.  [The docs](https://developer.android.com/reference/android/net/Uri) say "Behavior is undefined for invalid input." This means that we need something like if regex match ':' (or any character illegal in a querystring) then error out with "QR data contains bad characters".  It [looks like](https://stackoverflow.com/questions/2597653/validate-that-uri-is-valid-http-uri) Java has a URL object that might throw a catchable exception on parsing a URI (the object is URL but I don't have time for further research right now).

A catch for all possible exceptions in `static public BarcodeData parseMoneroUri(String uri)` seems like a simple fix, but wouldn't tell @Cactii1 that the colon was the problem.

**Comment by Cactii1** [comment]
The first one isn't valid because you can't specify a Payment ID like that anymore, you need to use an Integrated Address.

**Comment by m2049r** [comment]
all the above work - except the one with payment id which isnt supported any longer
