### ISSUE TITLE
Deal with manually entered integrated addresses

### ISSUE THREAD

**Issue by m2049r** [m2049r/xmrwallet#69]
It is possible to enter (also copy/paste) integrated addresses in the send screen - these are currently "invalid"

The app should either allow them or split them into address + payment id. (or both?)

Maybe a new field?

**Comment by stevesbrain** [comment]
It seems reasonable that you would be able to "detect" an integrated address based on length of string, yeah? If so, you could then handle it differently behind the scenes based on that?

**Comment by MBuffenoir** [comment]
Also, If I scan a qrcode of an integrated address, it is not recognized as a valid monero address ...

I only tried in testnet for now

**Comment by m2049r** [comment]
yes, this is true. for now.

**Comment by jonathancross** [comment]
I see https://github.com/m2049r/xmrwallet/pull/153/commits/521b73312251a61b4ba8169a009b7d5fdf630274  (scan integrated address) -- is support for integrated addresses still pending?

**Comment by MBuffenoir** [comment]
Hey Jonathan, it's done. Been using it for a while now.

Le ven. 4 mai 2018 à 17:59, Jonathan Cross <notifications@github.com> a
écrit :

**Comment by jonathancross** [comment]
Great!  This can be closed @m2049r
