### ISSUE TITLE
Inaccurate sync/scan progress displayed

### ISSUE THREAD

**Issue by leafcutterant** [m2049r/xmrwallet#696]
Many times the synchronization progress is displaying things that are either inaccurate or make no sense.

1. Negative remaining blocks to be scanned. E.g. "Scanning: -1,000 Blocks remaining"
2. Failing to take into account the real chain tip. E.g. "Synced 1,500,00", with the double check mark, when the real chain tip is block 2,000,000. This comes in three flavors:
    1. When the progress bar is at 0%
    2. When the progress bar is at 100%
    3. When the progress bar is somewhere in the middle

Overall, I think the current framework for letting the user know what is going on is insufficient. If you agree, I'll try to write up what I think would be an improvement over this.

**Comment by skorokithakis** [comment]
I have been seeing this issue too. I thought it was a Ledger issue but it seems to be more general.

**Comment by juanpc2018** [comment]
connect to:
node.supportxmr.com 18081
or to a private personal Desktop node 

it takes more time to connect but its "safe connect"...

probably must be your Android phone...
i have No problems here.

LG V10 aOS7
LG K40 aOS9

all brands of phones change the OS, google releases a generic OS,
manufaturers add & remove things..

for example:
Samsung and others do Not have: Screen: Keep Turned-On.

LG is far superior.
V are top of the line
G are Not as good.
Q
K
Ks are bigger screen/battery.

only V can be rooted by asking LG developer a file & giving them the Imei sn#.

**Comment by skorokithakis** [comment]
Hmm, that node does not work for me, that port doesn't seem to be open.

**Comment by m2049r** [comment]
@leafcutterant there are a bunch of broken nodes out there which report inaccurate blockheights - often even on purpose. do you have issues with monerujo when connected to your own node, knowing it's wellbehaved and properly synced?
