### ISSUE TITLE
Wallet not syncing

### ISSUE THREAD

**Issue by RemyBaligant** [m2049r/xmrwallet#697]
Hi,

I never had any problems with my wallet since today... it's stuck on "scanning 11422 blocks remaining".
I tried to uninstall and restore the wallet, problem is the same.
Any issues with servers ?
Thanks

**Comment by czr1210** [comment]
Confirming this issue. Did experience problems after XMR fork, but was working on this build. Now same issues as before updating

**Comment by m2049r** [comment]
check out https://www.reddit.com/r/Monero/comments/jv8v2r/psa_if_you_run_a_public_remote_node_please/

TL;DR: use an updated node (to v0.17.1.3)
