### ISSUE TITLE
Integrate changenow for receiving monero from btc and other coins

### ISSUE THREAD

**Issue by jm355** [m2049r/xmrwallet#704]
Similar to how you can send bitcoin with xmr.to, it would be cool if we could receive bitcoin with changenow.io

**Comment by sylph1o** [comment]
This point seems much more important now that [XMR.to has shut down](https://xmr.to/blog/job-done). ChangeNOW could be a replacement. Cake Wallet uses it as well.

**Comment by randomark** [comment]
ChangeNOW is not good. SideShift.ai and FixedFloat is nice replace.

**Comment by jm355** [comment]
What's wrong with changenow? Thanks for pointing out some alternatives thought

**Comment by randomark** [comment]
> What's wrong with changenow? Thanks for pointing out some alternatives thought

Block founds

**Comment by m2049r** [comment]
SideShift.ai implemented in #710

**Comment by m2049r** [comment]
other coins implemented in #714
