### ISSUE TITLE
Xmr.to Service Shutting Down

### ISSUE THREAD

**Issue by randomark** [m2049r/xmrwallet#709]
Xmr.to Service Shutting Down (View webisite) and no longer work on app, need a good replace.

**Comment by sylph1o** [comment]
#704 proposes ChangeNow.io.

Other services that I have noticed:
- SideShift.ai
- FixedFloat
- MorphToken

**Comment by randomark** [comment]
> #704 proposes ChangeNow.io.
> 
> Other services that I have noticed:
> 
>     * SideShift.ai
> 
>     * FixedFloat
> 
>     * MorphToken

MorphToken is a shit block Founds.

**Comment by m2049r** [comment]
SideShift.ai implemented in #710
