### ISSUE TITLE
Wrong Restore Height

### ISSUE THREAD

**Issue by juanpc2018** [m2049r/xmrwallet#712]
there is a problem with Restore Height since 4ever,
asks YYYY-MM-DD
if i input 20000000
starts from BLOCK 2000000, NOT date..

why do i need a day and a month? crazy.

Wallet Empty.
Re Scan does Not fix the problem.
i can change Passphrase but Not Restore Height.

---------------------
also
"Walled Passphase" is confusing, it should be "Password for Wallet Name".

---------------------

**Comment by m2049r** [comment]
i don't quite understand what issue you are having?

if you enter a blockheight, it uses a blockheight. if you enter a date, it uses a date.

wallet passphrase is the passphrase you need to open your wallet. the password is used for decrypting the wallet files. "for wallet name" makes no sense to me.

also, please open separate issues for separate issues.
