### ISSUE TITLE
Problem with new Exchange service on App (sideshift.ai)

### ISSUE THREAD

**Issue by randomark** [m2049r/xmrwallet#713]
As the title suggests, I have a problem with the new exchange on Monerujo.

When I try to send Bitcoins it always gives me this error:

"Service depositAmmount out of range"

I have tried with various amounts and different wallets. I am currently using the latest stable version of the app.

**Comment by m2049r** [comment]
did sideshift solve this for you? how?

**Comment by xmready** [comment]
I am having the same problem with Sideshift in Monerujo. I got it to work by shortening the decimal to only two places, but this isn't really an acceptable fix if you are trying to pay an exact amount. I already sent an email to Monerujo support. The amounts are definitely within the given range, so it should accept them regardless of having 7 decimal places or 2.

**Comment by m2049r** [comment]
unfortunately, their round to 6 decimal places when exchanging to BTC
