### ISSUE TITLE
Receiving address QR codes are malformed

### ISSUE THREAD

**Issue by 2mac** [m2049r/xmrwallet#718]
The QR codes generated by monerujo put the string "monero" before the address. I assume it is meant to put "monero:" but without the colon, it is invalid, and another monerujo wallet scanning it will refuse to accept it.

**Comment by pricead** [comment]
I think this was just fixed with this [pull request](https://github.com/m2049r/xmrwallet/pull/716) that was merged yesterday.

**Comment by 2mac** [comment]
yep, looks good
