### ISSUE TITLE
Can't validate wallet passphrase when restoring wallet from seed

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [m2049r/xmrwallet#720]
I am unable to provide a password for the wallet that is accepted. Thus, I am unable to restore a wallet from mnemonic seed.

The password is seemingly otherwise checked correctly. It says "Yeah baby, h4x0r style!" Nevertheless, it throws a warning on the right of the field (!) and is highlighted red. The "MAKE ME A WALLET ALREADY!" button remains white.

This issue exists if I type out the password manually, or if I paste in a strong password. I have been unable to restore a wallet because this field flag prevents me from proceeding.

Samsung Galaxy S20+
Android 11
Monerujo 1.7.7 'Druk' (7070)

**Comment by m2049r** [comment]
there are no hard checks on the password. something else is not filled in. maybe the wallet name is already in use (check the monerujo folder)?

**Comment by juanpc2018** [comment]
#1. 
No, XMR Wallet "monerujo" has confusing terms... for humans.

when restoring a wallet from Private Keys from another phone or a written paper, 
the passphrase is the New password you want to have in, the New wallet,
 when you log-in to the restored wallet. 

#2. 
if you have Fat fingers, and small phone, mistakes can happen...
you can delete and restore again... 
the private keys dont change.

you can set No password, and the password will be click enter button, 
if you try to enter any other password wont enter,
very clever & funny to ask a password when there is No password.. i love that.

#3. Anyway...
CakeWallet is very similar wallet to XMR monerujo, Cake was iOS only, has weird name, but they have created an Android version.
try if you find monerujo terms too confusing...
https://github.com/fotolockr/CakeWallet

#4. LG phones are better,
V are Top of the line, the only that can be rooted by asking developer.lg.com a file with your emai.
G Not as good..
K middle class slim screen,
Ks Big screen middle class.
Big screen = Big battery.

model 10 very old 2015,
20, 30, 35, 40,45, 50 60 Latest model.

**Comment by SamsungGalaxyPlayer** [comment]
![IMG_20210303_112156.jpg](https://user-images.githubusercontent.com/12520755/110034829-859c0a00-7d00-11eb-91a1-617e5969e513.jpg)

**Comment by m2049r** [comment]
this is somewhat funny - there was no monero on 2014-02-18. but there is a bug in the code which prevents taking pre-monero dates as blockheight 0. current implementation does not accept dates prior to 2014-05-05.
