### ISSUE TITLE
make: *** No rule to make target 'release-static-android-armv7-wallet_api'.  Stop

### ISSUE THREAD

**Issue by ghost** [m2049r/xmrwallet#721]
+ PATH=/usr/cmake-3.12.1-Linux-x86_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin make release-static-android-armv7-wallet_api -j4
make: *** No rule to make target 'release-static-android-armv7-wallet_api'.  Stop

guide me to fix it !...

**Comment by m2049r** [comment]
i am guessing you are not using my fork of monero with tweaks for monerujo: https://github.com/m2049r/monero/tree/release-v0.17.1.9-monerujo

**Comment by capital-hub** [comment]
-- Looking for -pie linker flag - found
-- Looking for -Wl,-z,relro linker flag
-- Looking for -Wl,-z,relro linker flag - found
-- Looking for -Wl,-z,now linker flag
-- Looking for -Wl,-z,now linker flag - found
-- Looking for -Wl,-z,noexecstack linker flag
-- Looking for -Wl,-z,noexecstack linker flag - found
-- Looking for -Wl,-z,noexecheap linker flag
-- Looking for -Wl,-z,noexecheap linker flag - not found
-- Using C security hardening flags: -Wformat -Wformat-security -fstack-protector -fstack-protector-strong
-- Using C++ security hardening flags: -Wformat -Wformat-security -fstack-protector -fstack-protector-strong
-- Using linker security hardening flags: -pie -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack
-- Enabling PIE executable
-- Found Boost Version: 106700
-- Could NOT find Readline (missing: Readline_INCLUDE_DIR Readline_LIBRARY)
-- Looking for rl_copy_text
-- Looking for rl_copy_text - not found
-- Looking for rl_filename_completion_function
-- Looking for rl_filename_completion_function - not found
-- Looking for rl_copy_text
-- Looking for rl_copy_text - not found
-- Looking for rl_filename_completion_function
-- Looking for rl_filename_completion_function - not found
-- Could not find GNU readline library so building without readline support
CMake Error at CMakeLists.txt:986 (message):
Could not find required header zmq.hpp

-- Configuring incomplete, errors occurred!

and also incomplete library generation , missing libraries are " libzmq.a , librandomx.a , libnet.a , libblocks.a , liblokimq.a " these libraries are missing, when i trying to run with skip this "Could not find required header zmq.hpp" in if conditions in CMakeLists.txt will you please help me

**Comment by m2049r** [comment]
how exactly are you getting this?

**Comment by capital-hub** [comment]
> how exactly are you getting this?

i don't know but whenever i run the Dockerfile in the external-libs/docker foleder , the error came and i over come this by skip using # in CMakeLists.txt 

see this .....



# find_path(ZMQ_INCLUDE_PATH zmq.h)
 find_library(ZMQ_LIB zmq)
 find_library(PGM_LIBRARY pgm)
 find_library(NORM_LIBRARY norm)
 find_library(SODIUM_LIBRARY sodium)

# if(NOT ZMQ_INCLUDE_PATH)
  # message(FATAL_ERROR "Could not find required header zmq.hpp")
# endif()
# if(NOT ZMQ_LIB)
  # message(FATAL_ERROR "Could not find required libzmq")
# endif()




after this i have successfully run the Docker and also Collect.sh also done ,  after that missing libraries are " libzmq.a , librandomx.a , libnet.a , libblocks.a , liblokimq.a " these libraries are not generated.

**Comment by capital-hub** [comment]
> how exactly are you getting this?

i don't know but whenever i run the Dockerfile in the external-libs/docker foleder , the error came and i over come this by skip using # in CMakeLists.txt

see this ..... original in CMakeLists.txt

 find_path(ZMQ_INCLUDE_PATH zmq.h)
 find_library(ZMQ_LIB zmq)
  find_library(PGM_LIBRARY pgm)
  find_library(NORM_LIBRARY norm)
  find_library(SODIUM_LIBRARY sodium)
 if(NOT ZMQ_INCLUDE_PATH)
 message(FATAL_ERROR "Could not find required header zmq.hpp")
 endif()
 if(NOT ZMQ_LIB)
 message(FATAL_ERROR "Could not find required libzmq")
 endif()


and i skip that using #...


# find_path(ZMQ_INCLUDE_PATH zmq.h)
# find_library(ZMQ_LIB zmq)
  find_library(PGM_LIBRARY pgm)
  find_library(NORM_LIBRARY norm)
  find_library(SODIUM_LIBRARY sodium)
# if(NOT ZMQ_INCLUDE_PATH)
# message(FATAL_ERROR "Could not find required header zmq.hpp")
# endif()
# if(NOT ZMQ_LIB)
# message(FATAL_ERROR "Could not find required libzmq")
# endif()

after this i have successfully run the Docker and also Collect.sh also done , after that missing libraries are " libzmq.a , librandomx.a , libnet.a , libblocks.a , liblokimq.a " these libraries are not generated.

**Comment by capital-hub** [comment]
i don't know but whenever i run the Dockerfile in the external-libs/docker foleder , the error came and i over come this by skip using # in CMakeLists.txt

see this ..... original in CMakeLists.txt

 find_path(ZMQ_INCLUDE_PATH zmq.h)
 find_library(ZMQ_LIB zmq)
  find_library(PGM_LIBRARY pgm)
  find_library(NORM_LIBRARY norm)
  find_library(SODIUM_LIBRARY sodium)
 if(NOT ZMQ_INCLUDE_PATH)
 message(FATAL_ERROR "Could not find required header zmq.hpp")
 endif()
 if(NOT ZMQ_LIB)
 message(FATAL_ERROR "Could not find required libzmq")
 endif()


and i skip that using #...


#find_path(ZMQ_INCLUDE_PATH zmq.h)
#find_library(ZMQ_LIB zmq)
  find_library(PGM_LIBRARY pgm)
  find_library(NORM_LIBRARY norm)
  find_library(SODIUM_LIBRARY sodium)
#if(NOT ZMQ_INCLUDE_PATH)
#message(FATAL_ERROR "Could not find required header zmq.hpp")
#endif()
#if(NOT ZMQ_LIB)
#message(FATAL_ERROR "Could not find required libzmq")
#endif()

after this i have successfully run the Docker and also Collect.sh also done , after that missing libraries are " libzmq.a , librandomx.a , libnet.a , libblocks.a , liblokimq.a " these libraries are not generated.

**Comment by capital-hub** [comment]
> how exactly are you getting this?

i don't know but whenever i run the Dockerfile in the external-libs/docker foleder , the error came and i over come this by skip using # in CMakeLists.txt

see this ..... original in CMakeLists.txt

 find_path(ZMQ_INCLUDE_PATH zmq.h)
 find_library(ZMQ_LIB zmq)
  find_library(PGM_LIBRARY pgm)
  find_library(NORM_LIBRARY norm)
  find_library(SODIUM_LIBRARY sodium)
 if(NOT ZMQ_INCLUDE_PATH)
 message(FATAL_ERROR "Could not find required header zmq.hpp")
 endif()
 if(NOT ZMQ_LIB)
 message(FATAL_ERROR "Could not find required libzmq")
 endif()


and i skip that using #...


#find_path(ZMQ_INCLUDE_PATH zmq.h)
#find_library(ZMQ_LIB zmq)
  find_library(PGM_LIBRARY pgm)
  find_library(NORM_LIBRARY norm)
  find_library(SODIUM_LIBRARY sodium)
#if(NOT ZMQ_INCLUDE_PATH)
#message(FATAL_ERROR "Could not find required header zmq.hpp")
#endif()
#if(NOT ZMQ_LIB)
#message(FATAL_ERROR "Could not find required libzmq")
#endif()

after this i have successfully run the Docker and also Collect.sh also done , after that missing libraries are " libzmq.a , librandomx.a , libnet.a , libblocks.a , liblokimq.a " these libraries are not generated.

**Comment by m2049r** [comment]
there is no `external-libs/docker` folder

**Comment by capital-hub** [comment]
Dude :
   It's there in XMR ANDROID WALLET

**Comment by m2049r** [comment]
the only folder inside `external-libs` is `include`. check for yourself => https://github.com/m2049r/xmrwallet/tree/master/external-libs

why don't you just use the supplied `Makefile` by running `make`? (you will need to put the monero sources in a folder named `monero` first though)

**Comment by m2049r** [comment]
@capital-hub DUDE: you are forking off oxen-io/loki-android-wallet (where there is a `docker` folder there)- maybe you want to be posting issues there!
