### ISSUE TITLE
Could not find required header zmq.hpp

### ISSUE THREAD

**Issue by capital-hub** [m2049r/xmrwallet#728]
-- Looking for -pie linker flag - found
-- Looking for -Wl,-z,relro linker flag
-- Looking for -Wl,-z,relro linker flag - found
-- Looking for -Wl,-z,now linker flag
-- Looking for -Wl,-z,now linker flag - found
-- Looking for -Wl,-z,noexecstack linker flag
-- Looking for -Wl,-z,noexecstack linker flag - found
-- Looking for -Wl,-z,noexecheap linker flag
-- Looking for -Wl,-z,noexecheap linker flag - not found
-- Using C security hardening flags:  -Wformat -Wformat-security -fstack-protector -fstack-protector-strong
-- Using C++ security hardening flags:  -Wformat -Wformat-security -fstack-protector -fstack-protector-strong
-- Using linker security hardening flags:  -pie -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack
-- Enabling PIE executable
-- Found Boost Version: 106700
-- Could NOT find Readline (missing: Readline_INCLUDE_DIR Readline_LIBRARY) 
-- Looking for rl_copy_text
-- Looking for rl_copy_text - not found
-- Looking for rl_filename_completion_function
-- Looking for rl_filename_completion_function - not found
-- Looking for rl_copy_text
-- Looking for rl_copy_text - not found
-- Looking for rl_filename_completion_function
-- Looking for rl_filename_completion_function - not found
-- Could not find GNU readline library so building without readline support
CMake Error at CMakeLists.txt:986 (message):
  Could not find required header zmq.hpp

-- Configuring incomplete, errors occurred!

and also incomplete library generation , missing libraries are " libzmq.a , librandomx.a , libnet.a , libblocks.a , liblokimq.a " these libraries are missing, when i trying to run with skip this "Could not find required header zmq.hpp" in if conditions in CMakeLists.txt will you please help me

**Comment by m2049r** [comment]
how exactly are you getting this?

**Comment by m2049r** [comment]
you are forking off `oxen-io/loki-android-wallet` - maybe you want to be posting issues there!
