### ISSUE TITLE
Does the crazypass contain whitespace?

### ISSUE THREAD

**Issue by geebotron** [m2049r/xmrwallet#736]
When using the crazypass, is it expected that a space is input between the 13 four-letter "words" that comprise the pass?

**Comment by m2049r** [comment]
if entered in the app, then no. also the letters can be entered upper or lowercase (or mixed).

if you use the wallet files on another device (i.e. a PC with the official clients), then the spaces are important, and all characters need to be upper case.

**Comment by geebotron** [comment]
Thanks
