### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by q7nm** [m2049r/xmrwallet#737]
Please, add support for proxy. For example, I want choose onion node, but for this need tor.

**Comment by ElonSatoshi** [comment]
I too would like native support for Tor in Monerujo. In the meantime, you can use Orbot's VPN mode to torify Monerujo.

**Comment by randomark** [comment]
> I too would like native support for Tor in Monerujo. In the meantime, you can use Orbot's VPN mode to torify Monerujo.

How to do this exactly?

**Comment by q7nm** [comment]
monerujo now supports TOR proxy.
