### ISSUE TITLE
External storage permissions?

### ISSUE THREAD

**Issue by jluttine** [m2049r/xmrwallet#738]
Hi! Thanks for Monerujo! I was surprised that the app asked for external storage permissions. Why does it need access to my photos and files in order to work?

**Comment by jluttine** [comment]
Ok, found this information from https://www.monerujo.io/privacy-policy.html - thanks for having it publicly available! I should've found it before posting this issue.

```
READ_EXTERNAL_STORAGE : Read wallet files stored on the device

WRITE_EXTERNAL_STORAGE : Write wallet files stored on the device
```



However, couldn't the wallet files be stored as app data? I'm not familiar with Android development, but many apps store various kinds of data without access to external storage. Isn't there a place for the apps to store their own data? If so, why not use that? Why the external storage?

**Comment by jluttine** [comment]
For instance, Green wallet for Bitcoin in Android doesn't require external storage permissions but still it somehow stores the wallet I suppose. So, why can't Monerujo do the same?

**Comment by colemickens** [comment]
It shouldn't need this even to be able to read/write files, it can ask the user to choose and grant access to a location without giving it access to everything. It is very concerning to me that it is left as-is. Further, it's _fully_ unnecessary for hardware wallet users.

**Comment by m2049r** [comment]
the way monero works is that it stores a local cache of the relevant transactions so it does not need to scan the blockchain again every time. so this is especially valuable to hardware wallet users @colemickens - image you had to scan the blockchain every time you opened up a ledger wallet...! this cache file also stores all notes and private send keys (needed to prove sending) as well as subaddress & account names. the keys file stores wallet data - not only the keys but also the restore height (also needed for hardware wallets).

granting access to a location (which the user has to create in this case, as we need a whole folder) is a nightmare for UX - explaining to a new user whats going on and what they need to do before ever seeing the app is not the way

having said all this, i will be rewriting the file handling code to use scoped storage in the next 1 or two releases. the downside is that the wallet with all its data will be deleted from the device when uninstalling the app *without warning*. this is also the reason why this was implemented the way it was to begin with.

but now, as there are more and more problems with foreign apps messing with the wallet files and creating problems for users and google forcing apps to use scoped storage, we will be moving in that direction.

**Comment by m2049r** [comment]
done.
