### ISSUE TITLE
How to crack wallets to get back Monero?

### ISSUE THREAD

**Issue by zyansheep** [m2049r/xmrwallet#743]
I gave some monero to a friend and then he forgot his wallet password. I know it wasn't a very good password because I remember him telling me what it was, so I was wondering if I could brute force it using hashcat. However, I'm not exactly sure how to go about extracting a hash from the backup wallet files.
Any ideas?

**Comment by juanpc2018** [comment]
Usually when Password is forgoten, the password is [Enter.] = No password.

the king of password recovery are:
https://parallelrecovery.com/wallet-password.html

ask them to make a custom version for Monero.

there are other options, BlackCat/hashcat, more difficult, you need to know the encription algorithm used by Wallet, and the file name.

P.D. you need the fastest CPU + GPU in the world if you want to finish in this life.

When password is forgotten, 
simply Delete the Wallet, and Restore Again from Private+Public Keys, Restore Height 0 or 1, 
thats the easy way...

IF also forgot the private+public keys, wrote wrong, etc... Delete&Restore is Not an option.
try to restore in a New / dfferent phone without deleting the other.
No keys? 
BruteForce Parallel Password recovery CPU+GPU is the Only option.

Dictionary Attack can be used if client remembers something about the password..
Has Upper case? or all are lower case?
has numbers only? letters only? or letters + numbers?
has simbols !"#$%&/ ?
those questions you must ask...

maybe hashcat can be modified to work with Amazon Cloud Servers...

some algorithms work better with Nvidia others with AMD, you must test.

**Comment by zyansheep** [comment]
I was planning on doing a dictionary attack. I can figure out how to brute force the password on my own, I just need to figure out how monerujo encrypts the private key with the password and/or how to extract a hash to brute force from the backup wallet files. (i.e. `wallet`, `wallet.address.txt` and `wallet.keys`)

**Comment by pricead** [comment]
Monerujo's "CrazyPass" is going to make cracking this almost impossible. Whatever password your friend used was then transformed using a device specific key that is going to be much stronger.

**Comment by zyansheep** [comment]
Is there any way I can get the device-specfic key from the device? How does that mechanism work?

**Comment by pricead** [comment]
> Is there any way I can get the device-specfic key from the device? How does that mechanism work?

Check this posted issue for further discussion:

https://github.com/m2049r/xmrwallet/issues/651

**Comment by zyansheep** [comment]
Ok
