### ISSUE TITLE
Sideshift didn't work from wallet, but manually sideshift worked fine. 

### ISSUE THREAD

**Issue by snaggen** [m2049r/xmrwallet#749]
I just tried to do a BTC payment on BitPay using Monerujo. It scanned the QR code fine, but then it could not contact sideshift. However, using sideshift.ai manually worked just fine.

**Comment by snaggen** [comment]
This was using version 1.18.1

**Comment by randomark** [comment]
How to solve manually?

**Comment by snaggen** [comment]
Just went to the sideshift homepage and created the transaction there.

**Comment by m2049r** [comment]
i guess their api endpoint was down. nothing much we can do about that. going there in a browser is a sensible workaround.
