### ISSUE TITLE
Upgrade gradlew wrapper scripts (./gradlew & ./gradlew.bat) & gradle

### ISSUE THREAD

**Issue by emanuelb** [m2049r/xmrwallet#758]
### Description

The `./gradlew` & `./gradlew.bat` files are old, the `./gradlew` require bash dependency which is removed in newer version, gradle version in distributionUrl (in file `gradle/wrapper/gradle-wrapper.properties`) was updated in the past without updating the related gradle scripts.

###  Expected behaviour

newer versions of the scripts are used which avoid the bash dependency, future updates to gradle will include updates to scripts as well.

### Additional info

running:

```shell
./gradlew wrapper --gradle-version 7.0
```

which is the command to upgrade the gradle wrapper:
https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper

will result in changes in both gradlew and gradlew.bat files.

the history of `./gradle/wrapper/gradle-wrapper.properties` shows that the gradle version was updated several times, but in each update the related wrapper files wasn't updated, thus in the future it's also recommended to run the above command when upgrading the gradle version (as it's change the gradle version in distributionUrl as well)

**Comment by m2049r** [comment]
fixed in #760
