### ISSUE TITLE
Can't import wallet on factory-resetted phone - Wrong password though it's the correct one 10000% certain

### ISSUE THREAD

**Issue by 1reverseengineer** [m2049r/xmrwallet#773]
I backuped my wallet and copied the zip on a drive. Factory-Resetted the phone, reinstalled moneroju and imported the wallet.
Upon entering in my old same password in the password prompt, I get 'Wrong Password' each time.

Why is that? I also removed the cache file from the zip (copy), as someone noted an issue on reddit.
I backed up all the wallet info on paper months ago on creation, but can't access it for some weeks rn.

I am certain, it's the same password 10000000%.

Also the Crazypass Whitepaper is 404 on github.

**Comment by m2049r** [comment]
you would need the backup password aka crazypass to recover the backups. we are reworking wording and some screens to make the more clear. use your seed to recreate the wallet.

the whitepaper is here https://www.monerujo.io/resources/crazy_secure_passphrase.pdf

**Comment by 1reverseengineer** [comment]
> you would need the backup password aka crazypass to recover the backups. we are reworking wording and some screens to make the more clear. use your seed to recreate the wallet.
> 
> the whitepaper is here https://www.monerujo.io/resources/crazy_secure_passphrase.pdf

Thanks. I am not quite sure if I understand the entire procedure correctly but it seems like I need the backup paper one way or another, no way around that.
Still thanks for your help, I will mark this issue as solved.
*Cant close the issue myself, would appreciate it if a mod quickly closes this issue thanks.

**Comment by 1reverseengineer** [comment]
> you would need the backup password aka crazypass to recover the backups. we are reworking wording and some screens to make the more clear. use your seed to recreate the wallet.
> 
> the whitepaper is here https://www.monerujo.io/resources/crazy_secure_passphrase.pdf

I've access to my wallet paper again. Now I see what you mean by Crazypass recovery. It's made up of 13 words upon creation under the 25 word seed right? 
Yeah that needs a rewording.

I have everything, the 25 word seed, the creation height, the 13x4 blocks crazypass thing that is made up of captial letters and numbers.
Yet when I click on recover from seed, type in a wallet name, a password, the 25 word seed that I wrote down and creation height (although I read, that it doesn't matter, just a date before the wallet was created), I get an "Electrum style word list verification" error. 
I checked every word with multiple electrum/ monero word lists online, every word is correct. There's one word which is odd ("buys") and I tested different words from the electrum word lists that sound/are somewhat the same (buying, buy, guys, those are the only ones to have uys, ys in them).

I don't understand. Why is it not working? Do you have to type them as one giant string ? Do you have to write them all in capital letters? Newlines ? 

Also, when I add the monero backup wallet file, do I have to type in the crazypass in the password field with or without spaces?

The whole backup and wallet restore thing has been very horrific and definitely not on par with the usual nice moneroju expierence. There's definitely some work there that needs to be done.

**Comment by m2049r** [comment]
> There's definitely some work there that needs to be done.

this.

- the 13x4 blocks crazypass can be entered any way you like: upper/lowercase & with/without spaces
- the seed words should be lower case, with blanks inbetween words. entering the first three letters of each word should be enough.
- check out the monero wordlist: https://github.com/monero-project/monero/blob/master/src/mnemonics/english.h
