### ISSUE TITLE
While building the android32.DockerFile error occurs

### ISSUE THREAD

**Issue by MichaleAnderson** [m2049r/xmrwallet#777]
Step 45/46 : RUN set -x     && cd /src     && CMAKE_INCLUDE_PATH="${PREFIX}/include"        CMAKE_LIBRARY_PATH="${PREFIX}/lib"        ANDROID_STANDALONE_TOOLCHAIN_PATH=${TOOLCHAIN_DIR}        USE_SINGLE_BUILDDIR=1        PATH=${HOST_PATH} make release-static-android-armv7-wallet_api -j${NPROC}
 ---> Running in c71b4da576f6
+ cd /src
+ CMAKE_INCLUDE_PATH=/opt/android/prefix/include CMAKE_LIBRARY_PATH=/opt/android/prefix/lib ANDROID_STANDALONE_TOOLCHAIN_PATH=/opt/android/toolchain- USE_SINGLE_BUILDDIR=1 PATH=/usr/cmake-3.14.6-Linux-x86_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin make release-static-android-armv7-wallet_api -j4
make: *** No rule to make target 'release-static-android-armv7-wallet_api'.  Stop.

**Comment by m2049r** [comment]
you need the monero fork with the monerujo tweaks. current one is https://github.com/m2049r/monero/tree/release-v0.17.2.0-monerujo
