### ISSUE TITLE
Building the ext libs 

### ISSUE THREAD

**Issue by reppolice** [m2049r/xmrwallet#78]
Hi,

Regarding https://github.com/m2049r/xmrwallet/blob/master/doc/BUILDING-external-libs.md
The instructions have some inaccuracies, most notably they do not mention installing clang, a wget is missing from the boost download, the first apt-install is a typo that either needs the - removed or converted to "apt-get install", and now the sticky part, libzmq! Cmake cannot find it when "building monero". I had libzmq3 on my Ubuntu 16.04, probably got it to compile Monero4ubuntu, replaced it with libzmq which changed nothing, then I realized the 32 bit version may be needed, I got one but still cmake is not interested. Is this the kind of thing I should try and solve by tweaking cmake internals, or should libzmq be added to the instructions from source perhaps?
Thanks!

**Comment by m2049r** [comment]
typo: yes, thanks. i did not have to install clang explicitly on my fresh 16.04 ubuntu.

the monero master branch does not build - for me neither android nor "normal" ubuntu builds.  the instructions work well for the release-v0.11.0.0

if you figure out how to make it build again please tell me here.  thanks.

maybe we should post an issue in the monero repo.

**Comment by m2049r** [comment]
@reppolice clang is in the android NDK - if you have set the PATH ocrrectly it will be found.

**Comment by reppolice** [comment]
re: clang, I followed the recipe and it did not seem to be on the PATH, while everything else seemed to be there, anyway, your previous answer implies bigger headaches elsewhere!

**Comment by m2049r** [comment]
```
m2049r@ubex:~$ which clang
/opt/android/tool32/bin/clang
```

**Comment by m2049r** [comment]
BUILDING-external-libs.md updated
