### ISSUE TITLE
Public Keys?

### ISSUE THREAD

**Issue by RobioEpo** [m2049r/xmrwallet#799]
Why doesn't the app show the public keys?

**Comment by m2049r** [comment]
what use do you have for the public keys?

**Comment by RobioEpo** [comment]
Just wondering, I have no need for it really.

**Comment by m2049r** [comment]
that's your answer :)
there is no real use for the public keys - they are actually part of the monero address. you can play with them here: https://xmr.llcoins.net/addresstests.html starting from number 8.
