### ISSUE TITLE
F-Droid repo strangeness

### ISSUE THREAD

**Issue by jahway603** [m2049r/xmrwallet#801]
The desription of this issue is here: https://forum.f-droid.org/t/monerujo-repository-acting-strange/16052

**Comment by goyalyashpal** [comment]
> The desription of this issue is here: ...

ahw, bad method @jahway603 please share the description here.

**Comment by yashpalgoyal1304** [comment]
@jahway603

**Comment by jahway603** [comment]
I just added and enabled the Monerujo repository and am able to download the apps it provides, but when I go to my repository settings and click to see the repo’s information it says:

“This repository has not been used yet. You need to enable it to view the apps it provides.”

Again, it is enabled and I can download the apps. I just can’t see the repository’s description, fingerprint, and number of apps included. I’ve tried disabling and re-enabling the repo, removing and re-adding it, and restarting my phone. And yes, after enabling the repo I am waiting for the repositories to update.

It only seems to be a problem with the Monerujo repo, as I’ve tested the Bromite and MicroG repositories and they work as expected.

Is this something I should be concerned about or just a superficial thing?

Any help is greatly appreciated. Thank you.

**Comment by m2049r** [comment]
you probably did not enter the fingerprint when adding the repo. if you use the qrcode on https://f-droid.monerujo.io/ it will add the fingerprint for you. or you have to enter it in the 'Fingerprint' field when adding manually.

**Comment by jahway603** [comment]
Unsure of what happened @m2049r, as I did not change anything on my end, but now the repo info appears correctly. What changed on the f-droid.monerujo.io end?

**Comment by goyalyashpal** [comment]
> I’ve tried disabling and re-enabling the repo, removing and re-adding it, and restarting my phone

did u try to clear the cache of fdroid client app? and if that didnt work, then clearing its data `/!\ will remove all additional repos` ??

**Comment by jahway603** [comment]
> Unsure of what happened @m2049r, as I did not change anything on my end, but now the repo info appears correctly. What changed on the f-droid.monerujo.io end?

Hi @yashpalgoyal1304, did you see this comment from yesterday?

**Comment by goyalyashpal** [comment]
the cache clearing action needs not to be performed explicitly by the user... some apps can do that as well. so... can u check the cache & data size of fdroid app. if cache size is very small, then it's likely it was cleared.

**Comment by m2049r** [comment]
> Unsure of what happened @m2049r, as I did not change anything on my end, but now the repo info appears correctly. What changed on the f-droid.monerujo.io end?

haven't touched it. maybe the f-droid app took some time to sync / verify / whateveritdoes?
