### ISSUE TITLE
Crash when save or test node

### ISSUE THREAD

**Issue by nahuhh** [m2049r/xmrwallet#818]
1. Add node ip and port. Leave name(optional) blank
2. Tap save or test
3. App crashes

Workaround
Add a name

**Comment by m2049r** [comment]
can you give more info on your setup. i cannot reproduce this.

**Comment by nahuhh** [comment]
> can you give more info on your setup. i cannot reproduce this.

Enter node ip
Enter node port
Leave all other fields empty

Tap test = crash
Tap ok = crash

2devices, different os version and manufacturer. Fresh install.

Fix
Add a name

Probably related.
Im unable to delete the name. Deleting the name results in nothing. The name remains the same.
