### ISSUE TITLE
Unable to connect to my any Monero node (public or private)

### ISSUE THREAD

**Issue by jahway603** [m2049r/xmrwallet#830]
I am not able to connect to my 192.x internal monero nodes. This feature was working at least during the end of last year. 
I am not able to create nodes in Monerujo (#818 and #827) and I am unable to connect to my nodes which were configured in the wallet at the end of last year. It does not matter if a name is used for coniguration or not - it does not want to connect to the nodes.

For our "control group", I am able to connect to my monero nodes using the official desktop wallet on the same network.

**Comment by jahway603** [comment]
More details
* Monerujo version 2.4.1 from F-Droid
* Android 12
* The server "Test" works in the config options of the server
* Wallet states invalid login/password when trying to use the server, but the same info works correctly on the desktop wallet to connect to the remote node.

**Comment by nahuhh** [comment]
Just to confirm for testing,
Do you have a username and password set?

**Comment by jahway603** [comment]
I do have a username and password set. They function correctly as expected with the monerod running on my server from the desktop wallet on my workstation (the wallet and monerod are on separate computers).

Port 18081 is forwarded from my firewall. In Monerujo, I can configure the node and when clicking on "Test" it will test fine but it will not connect to the node and use it. I was using Monerujo with two other monerod nodes last year before I took them offline, so I know it has worked in the past. Please let know what other information I can provide.

**Comment by nahuhh** [comment]
> I do have a username and password set. They function correctly as expected with the monerod running on my server from the desktop wallet on my workstation (the wallet and monerod are on separate computers).
> 

I can confirm that after setting a password,l:
I **can** connect to my 192.168.x.x address over WiFi from my mobile to my node

> Port 18081 is forwarded from my firewall. 
>
Router port forwarding shouldn't be necessary.
If running Linux, make sure the port is open in ufw / gufw etc. 

> In Monerujo, I can configure the node and when clicking on "Test" it will test fine but it will not connect to the node and use it. I was using Monerujo with two other monerod nodes last year before I took them offline, so I know it has worked in the past. Please let know what other information I can provide.
>

If im being perfectly honest, I hope screenshots/recording come to the next version because i can never connect on launch. Takes me like 10 attempts to get it to show the node.
.. but I was able to connect and sync with a username and password

**Comment by jahway603** [comment]
I tried again - Monerujo starts to sync and then spits that it's an invalid username and password when it is not. I tried on local WiFi and over the cell network but both fail.

I'm using GrapheneOS, which I do not believe to be a factor since this was working perfectly fine all last year with the same phone & OS.

**Comment by nahuhh** [comment]
@m2049r

**Comment by jahway603** [comment]
I tried this again using the public node.supportxmr.com node, so no login and password is required. It worked perfectly on the Monero desktop wallet.

When I tried this public node on Monerujo, it failed to work on either WiFi or cell network with it.

**Comment by jahway603** [comment]
Changed issue topic title as I tried to receive in-person payment yesterday using this wallet, tried numerous public nodes, and none of it worked. I had to use a different wallet and still feel dirty about it.

**Comment by nahuhh** [comment]
Have you tried to uninstall and reinstall monerujo? Backup seeds first of course. 

Or, create a work profile using Shelter (f droid), install monerujo there and see if monerujo is working inside of the work profile

**Comment by jahway603** [comment]
I've tried two things, which both worked, so I'm not sure of the root cause of the issue I'm having, but am closing this.
1. Created new wallet in Monerujo on the "problem phone" and that worked perfectly fine with my node as expected, where-as the "problem wallet" is still not on this phone.
1. Installed Monerujo on a new GrapheneOS phone, restored "problem wallet" from seed and it works perfectly fine with my node as expected.
