### ISSUE TITLE
[Documentation] What is shared with the public monerod node?

### ISSUE THREAD

**Issue by maltfield** [m2049r/xmrwallet#847]
This is a request to add to the FAQ a section that tells the user exactly what is shared with the public node by this wallet

 * https://github.com/m2049r/xmrwallet/blob/master/doc/FAQ.md

I noticed that the MyMonero wallet website states that it shares the "view key" with their servers:

> only your "view key" is shared with the server.

 * source: https://mymonero.com/

Question: Does Monerujo also share the "view key" with the server?

**Comment by m2049r** [comment]
monerujo does not share the view key (mymonero scans for you and so needs the view key)

**Comment by maltfield** [comment]
@m2049r thanks for answering my question, but I believe this issue was closed prematurely.

This issue was created to *document* a list of all of "what is shared with the server" in the FAQ.

Can you please re-open until this info has been documented somewhere (eg the [FAQ page](https://github.com/m2049r/xmrwallet/blob/master/doc/FAQ.md))?
