### ISSUE TITLE
Set new wallets' restore height correctly

### ISSUE THREAD

**Issue by mstniy** [m2049r/xmrwallet#857]
Currently new wallets' restore height is set to 2000 blocks below the current one. I can't see the reasoning behind this, and it leads to the wallet scanning blocks needlessly.

See [LoginActivity.java](https://github.com/m2049r/xmrwallet/blob/c956f38899fb85594d40cf6fa7631164bbab2689/app/src/main/java/com/m2049r/xmrwallet/LoginActivity.java#L921)

**Comment by pricead** [comment]
Are some historical blocks not needed by the wallet for possible decoy selection?
