### ISSUE TITLE
Monerujo used up ~8 GB of data in one day

### ISSUE THREAD

**Issue by kristianbrox** [m2049r/xmrwallet#862]
monerujo has used a lot of data in the last 24 hours. It seems like it could have used more than 8 GB, but my data provider cut my traffic due to my data plan.

I'm using the f-droid version (2.4.3 Baldau 14030), connected to a self hosted node (v0.18.0.0 Fluorine Fermi) 

Could it be related to the hard fork?

**Comment by m2049r** [comment]
this may (or may not) be monerujo trying to pull data off the node,  but the monerujo you are using is not based on v0.18 - use release v3.0.2

**Comment by kristianbrox** [comment]
This seems plausible. I'm on v3.0.2 now, and everything seem to work fine.
