### ISSUE TITLE
Wallets from Google Play unusable currently

### ISSUE THREAD

**Issue by AadaEa** [m2049r/xmrwallet#871]
Hello,

I downloaded Monerujo and Wonerujo a few days ago, whenever I try to open a wallet I created, the wallet "crashes".

I type the password, I see a loading process, "Loading wallet..." displayed, and before the loading bar completes, I get kicked back into the app home screen, with an empty system notification (the notification that displays at the bottom of the screen for a few seconds). I see the icon of the app, but the string is empty, giving no indication about the error.

I tried to delete and create new wallets, same issue.

Google pixel 4, android (last version), changing the language doesn't correct the issue.

I'm afraid this issue is causing plenty of 1 star marks on google play both for the monero and the wownero wallet.

Thanks.

**Comment by Telsbat** [comment]
For me issue happening only when i use mobile data, with wifi works great. But yes it's actually unusable with this issue

**Comment by Enkimin** [comment]
Same issue. 

I haven't tested on wifi yet but Ill do so in a few hours. On a pixel 4a + calxy and mobile data installed from F-droid. wallet will load about a 1/4 if the time if it does not kick me back to the main screen. If it does load the connection hangs or is abysmally slow. 

tested on both Tor and clearnet with nodes that I have a "strong" signal.

ill report back with more detailed info when I can.

**Comment by AadaEa** [comment]
Apparently it works on wifi, but not on 4G/5G. I don't get it. It shall work in 4G/5G because it is a mobile app.

**Comment by m2049r** [comment]
it seems that some networks block monero ports and so it crashes without an error message. its a pain.
