### ISSUE TITLE
RUB currency does not work

### ISSUE THREAD

**Issue by Wjxfi** [m2049r/xmrwallet#884]

**Comment by chaserene** [comment]
@m2049r w.r.t. 11b7e23: it's a bad idea to remove currencies as long as they are in use. especially when it's the local currency in a region with high inflation and rampant capital controls. people there need Monero to be usable the most.

how about retrieving RUBUSD from e.g. XE.com or another service, and multiply XMRUSD by it?

**Comment by m2049r** [comment]
surely. it was not removed because we don't like it. it was removed because it was broken. when we implement another exchange provider, it will be enabled again. together with a bunch of other currencies experiencing the problems you describe

**Comment by m2049r** [comment]
added in #921
