### ISSUE TITLE
Will other apps steal and obtain the private key if I don't set a password on monerujo?

### ISSUE THREAD

**Issue by hitczw** [m2049r/xmrwallet#910]

**Comment by d-Martian** [comment]
Your android device should be running an OS that prevents apps from having such access, but this app has no control over the OS security. Wallet passwords let the app keep your secret keys even more secure, even if the OS security fails.

**Comment by m2049r** [comment]
even if you don't set a password, the wallet files are encrypted with a generated password kept in a the secure element on the device - you can check the actual password used on the "secrets screen" (recovery password). this is the password you can use to open the wallet files on another device/PC. if you use a password, the secure element password is still used in combination with your chosen password to make a supersecure password even if use use simple password. make sure to write down the recovery password if you make backups.
