### ISSUE TITLE
Google play store displays app as harmful 

### ISSUE THREAD

**Issue by x64x2** [m2049r/xmrwallet#920]
I don't know if I'm the only one but I'm trying to install monerujo from Fdroid and I'm getting harmful app intent from the Google play store ![Hgrr.jpg](https://github.com/m2049r/xmrwallet/assets/81354428/5ea550c9-c186-4e0c-ad4f-d10c270e263b)

**Comment by m2049r** [comment]
what does "more details" say?

**Comment by xcpn** [comment]
> what does "more details" say?

This is what's been displayed, I just tried to download and got the same warning.

You can tap on _Install anyway_, but the warning is not encouraging!

![monerujo.jpg](https://github.com/m2049r/xmrwallet/assets/134593944/b7f193c6-db4a-4d03-adb4-665927de7fd6)

Installing via Play Store and not F-Droid the warning is not triggered by Play Protect.

**Comment by maridonkers** [comment]
Installing latest GitHub build also displays this warning. I'm contemplating on whether to install this version or not (has malware inadvertently been hacked into the build process, somehow). Version in Play Store installed without warning.

**Comment by anhdres** [comment]
It used to be the case that only some Xiaomi/Avast/McAfee devices were giving out a warning, not it seems like Google jumped into that wagon. Basically they flag anything with Monero code inside as a malware, probably due to some malwares using background Monero mining.
We're trying to get it whitelisted somehow but so far no luck.

**Comment by baltazartroisville** [comment]
Monerujo is the only xmr enabled wallet app that gives me that same malware warning.

**Comment by anhdres** [comment]
Nowadays I'm still getting the notice but luckily they added a "check or verify or scan app" thing that says the app is safe. I realize this may still be scary if you're a new user, but I'm afraid we'll keep getting this kind of unnecessary frictions with anything that is Monero related in the future.

**Comment by m2049r** [comment]
there is not much we can do here. gogole now occasionally asks to scan the app and then says it's safe, which may even look safer as it was scanned in front of your eyes and is safe right now
