### ISSUE TITLE
Zero balance

### ISSUE THREAD

**Issue by coffseducation** [m2049r/xmrwallet#973]
Hello,

I have monero on a Mymonero wallet.
I used the restore function with 25 words on the Monerujo Android wallet.
Balance however is (incorrectly) zero!

The information for restore looks correct, so where is my monero??

**Comment by Angiepeck22** [comment]
Hello @coffseducation 
 If your Monero balance isn't showing up correctly after using the restore function, . It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID MON07638
Please see the link below to our dedicated support line:
[Monero wallet Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by coffseducation** [comment]
I opted for another wallet. Thanks.
